/*
* This code was generated by df_game_data https://github.com/Atrix256/df_game_data
* Do not edit manually, unless you understand the consequences.
*/

#pragma once

#include <stdint.h>
#include <stdio.h>
#include <cstring>
#include <algorithm>

class dfgd
{
public:
    ~dfgd();

    // Note: the memory will be modified, and it must stay around for the life of the object.
    bool LoadFromMemory(void* mem, uint32_t size);

    bool LoadFromFile(const char* fileName);

public:
    template <typename T>
    union Ptr64
    {
        T* ptr;
        uint64_t _64 = 0;
    };

    struct Bool
    {
        uint8_t _8 = 0;
        bool Get() const
        {
            return _8 != 0;
        }
    };

    template <typename T>
    struct Record
    {
    public:
        const T& Get() const
        {
            static const T s_dummy = T();
            return m_record ? *m_record : s_dummy;
        }

        bool Valid() const
        {
            return m_record != nullptr;
        }

    private:
        friend class dfgd;
        T* m_record = nullptr;
    };

public:
    #pragma pack(push, 1)

    enum class EyeColor : uint16_t
    {
        Brown,
        Hazel,
        Blue,
        Green,
    };

    enum class Alignment : uint16_t
    {
        Good,
        Neutral,
        Evil,
    };

    enum class Class : uint16_t
    {
        Warrior,
        Wizard,
        Cleric,
        Druid,
    };

    struct Vec3
    {
        float x;
        float y;
        float z;
    };

    using Vec3Record = Record<Vec3>;

    struct Item
    {
        Ptr64<char> name;
    };

    using ItemRecord = Record<Item>;

    struct Character
    {
        Ptr64<char> name;
        EyeColor eyeColor;
        Alignment alignment;
        Class playerClass;
        Ptr64<Character> bestFriend;
        Vec3 location;
        uint16_t max_hp;
        static const uint32_t _other_numbers_count = 4;
        uint16_t other_numbers[4];
        static const uint32_t _other_inventory_count = 2;
        Ptr64<Item> other_inventory[2];
        uint16_t max_mp;
        Bool playable;
        uint32_t _favorite_numbers_count = 0;
        Ptr64<uint16_t> favorite_numbers;
        uint32_t _inventory_count = 0;
        Ptr64<Ptr64<Item>> inventory;
    };

    using CharacterRecord = Record<Character>;

    #pragma pack(pop)

private:
    template <typename T>
    inline static void EndianSwap(T& v)
    {
        uint8_t* bytes = reinterpret_cast<uint8_t*>(&v);
        for (size_t i = 0; i < sizeof(T) / 2; ++i)
        {
            uint8_t tmp = bytes[i];
            bytes[i] = bytes[sizeof(T) - 1 - i];
            bytes[sizeof(T) - 1 - i] = tmp;
        }
    }

    template <typename T>
    static bool Read(T& value, void* mem, uint32_t& memIndex, uint32_t memSize, bool endianSwap)
    {
        if (memSize - memIndex < sizeof(value))
            return false;

        memcpy(&value, &((char*)mem)[memIndex], sizeof(value));
        memIndex += sizeof(value);

        if (endianSwap)
            EndianSwap(value);

        return true;
    }

private:
    template <typename T>
    inline static void DoPointerFixup(T& v, void* base)
    {
    }

    template <typename T>
    inline static void DoPointerFixup(T*& v, void* base)
    {
        v = reinterpret_cast<T*>(reinterpret_cast<uintptr_t>(base) + reinterpret_cast<uintptr_t>(v));
    }

    template <typename T>
    inline static void DoPointerFixup(Ptr64<T>& v, void* base)
    {
        // null ptrs are preserved.
        if (v._64 == 0)
            return;
        v._64 += reinterpret_cast<uintptr_t>(base);
    }

private:
    template <typename T>
    inline static void DoEndianSwapAndPointerFixup(T& v, void* base, bool endianSwap)
    {
        if (endianSwap)
            EndianSwap(v);
        DoPointerFixup(v, base);
    }

    static void DoEndianSwapAndPointerFixup(Vec3& v, void* base, bool endianSwap);
    static void DoEndianSwapAndPointerFixup(Item& v, void* base, bool endianSwap);
    static void DoEndianSwapAndPointerFixup(Character& v, void* base, bool endianSwap);

private:
    uint8_t* m_ownedMemory = nullptr;

public:
    uint32_t GetCharacterCount() const
    {
        return m_table_Character_count;
    }

    CharacterRecord GetCharacter(uint32_t index) const
    {
        CharacterRecord ret;
        if (index < m_table_Character_count)
            ret.m_record = &m_table_Character.ptr[index];
        return ret;
    }

    CharacterRecord GetCharacter(const char* name) const
    {
        CharacterRecord ret;

        char** array = m_table_Character_names.ptr;
        const uint32_t count = m_table_Character_count;

        auto it = std::lower_bound(
            array,
            array + count,
            name,
            [](const char* item, const char* val)
            {
                return strcmp(item, val) < 0;
            }
        );
        uint32_t index = uint32_t(it - array);
        if (index < count && !strcmp(*it, name))
            ret.m_record = &m_table_Character.ptr[index];

        return ret;
    }

    uint32_t GetItemCount() const
    {
        return m_table_Item_count;
    }

    ItemRecord GetItem(uint32_t index) const
    {
        ItemRecord ret;
        if (index < m_table_Item_count)
            ret.m_record = &m_table_Item.ptr[index];
        return ret;
    }

    ItemRecord GetItem(const char* name) const
    {
        ItemRecord ret;

        char** array = m_table_Item_names.ptr;
        const uint32_t count = m_table_Item_count;

        auto it = std::lower_bound(
            array,
            array + count,
            name,
            [](const char* item, const char* val)
            {
                return strcmp(item, val) < 0;
            }
        );
        uint32_t index = uint32_t(it - array);
        if (index < count && !strcmp(*it, name))
            ret.m_record = &m_table_Item.ptr[index];

        return ret;
    }

private:
    uint32_t m_table_Character_count = 0;
    Ptr64<char*> m_table_Character_names;
    Ptr64<Character> m_table_Character;

    uint32_t m_table_Item_count = 0;
    Ptr64<char*> m_table_Item_names;
    Ptr64<Item> m_table_Item;
};

// ================================= Misc =================================

dfgd::~dfgd()
{
    delete[] m_ownedMemory;
    m_ownedMemory = nullptr;
}

inline constexpr uint32_t MakeFourCC(char a, char b, char c, char d)
{
    return (uint32_t)(uint8_t)a
        | ((uint32_t)(uint8_t)b << 8)
        | ((uint32_t)(uint8_t)c << 16)
        | ((uint32_t)(uint8_t)d << 24);
}

// ================================= LOADING =================================

bool dfgd::LoadFromMemory(void* mem, uint32_t memSize)
{
    uint32_t memIndex = 0;

    // verify fourcc, and see if we need to do endian swaps
    bool endianSwap = false;
    {
        static const uint32_t fourcc_regular = MakeFourCC('D', 'F', 'G', 'D');
        static const uint32_t fourcc_swapped = MakeFourCC('D', 'G', 'F', 'D');

        uint32_t fourcc = 0;
        if (!Read(fourcc, mem, memIndex, memSize, false))
            return false;

        if (fourcc == fourcc_swapped)
            endianSwap = true;
        else if (fourcc != fourcc_regular)
            return false;
    }

    // Verify that the schema hash in the binary data matches the schema hash this file was made for
    {
        uint64_t hash = 0;
        if (!Read(hash, mem, memIndex, memSize, endianSwap) || hash != 0xcd0634345d2ee752ULL)
            return false;
    }

    // Character Table
    {
        if (!Read(m_table_Character_count, mem, memIndex, memSize, endianSwap))
            return false;

        if (m_table_Character_count > 0)
        {
            // get char** to LUT and fixup string pointers
            if (memSize - memIndex < m_table_Character_count * sizeof(uint64_t))
                return false;
            m_table_Character_names._64 = memIndex;
            DoEndianSwapAndPointerFixup(m_table_Character_names, mem, endianSwap);
            for (uint32_t i = 0; i < m_table_Character_count; ++i)
                DoEndianSwapAndPointerFixup(m_table_Character_names.ptr[i], mem, endianSwap);
            memIndex += m_table_Character_count * sizeof(uint64_t);

            // Get a pointer to the first entry in the table
            if (memSize - memIndex < m_table_Character_count * sizeof(Character))
                return false;
            m_table_Character._64 = memIndex;
            DoEndianSwapAndPointerFixup(m_table_Character, mem, endianSwap);
            memIndex += m_table_Character_count * sizeof(Character);

            // Do pointer fixup
            for (uint32_t i = 0; i < m_table_Character_count; ++i)
                DoEndianSwapAndPointerFixup(m_table_Character.ptr[i], mem, endianSwap);
        }
    }

    // Item Table
    {
        if (!Read(m_table_Item_count, mem, memIndex, memSize, endianSwap))
            return false;

        if (m_table_Item_count > 0)
        {
            // get char** to LUT and fixup string pointers
            if (memSize - memIndex < m_table_Item_count * sizeof(uint64_t))
                return false;
            m_table_Item_names._64 = memIndex;
            DoEndianSwapAndPointerFixup(m_table_Item_names, mem, endianSwap);
            for (uint32_t i = 0; i < m_table_Item_count; ++i)
                DoEndianSwapAndPointerFixup(m_table_Item_names.ptr[i], mem, endianSwap);
            memIndex += m_table_Item_count * sizeof(uint64_t);

            // Get a pointer to the first entry in the table
            if (memSize - memIndex < m_table_Item_count * sizeof(Item))
                return false;
            m_table_Item._64 = memIndex;
            DoEndianSwapAndPointerFixup(m_table_Item, mem, endianSwap);
            memIndex += m_table_Item_count * sizeof(Item);

            // Do pointer fixup
            for (uint32_t i = 0; i < m_table_Item_count; ++i)
                DoEndianSwapAndPointerFixup(m_table_Item.ptr[i], mem, endianSwap);
        }
    }

    return true;
}

bool dfgd::LoadFromFile(const char* fileName)
{
    FILE* file = nullptr;
    fopen_s(&file, fileName, "rb");
    if (!file)
        return false;

    fseek(file, 0, SEEK_END);
    uint32_t fileSize = (uint32_t)ftell(file);

    m_ownedMemory = new uint8_t[fileSize];
    fseek(file, 0, SEEK_SET);

    if (fread(m_ownedMemory, fileSize, 1, file) != 1)
        return false;

    fclose(file);

    bool ret = LoadFromMemory(m_ownedMemory, fileSize);

    return ret;
}

// ================================= Pointer Fixup =================================

void dfgd::DoEndianSwapAndPointerFixup(Vec3& v, void* base, bool endianSwap)
{
    DoEndianSwapAndPointerFixup(v.x, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.y, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.z, base, endianSwap);
}

void dfgd::DoEndianSwapAndPointerFixup(Item& v, void* base, bool endianSwap)
{
    DoEndianSwapAndPointerFixup(v.name, base, endianSwap);
}

void dfgd::DoEndianSwapAndPointerFixup(Character& v, void* base, bool endianSwap)
{
    DoEndianSwapAndPointerFixup(v.name, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.eyeColor, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.alignment, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.playerClass, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.bestFriend, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.location, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.max_hp, base, endianSwap);
    for (uint32_t i = 0; i < v._other_numbers_count; ++i)
        DoEndianSwapAndPointerFixup(v.other_numbers[i], base, endianSwap);
    for (uint32_t i = 0; i < v._other_inventory_count; ++i)
        DoEndianSwapAndPointerFixup(v.other_inventory[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v.max_mp, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.playable, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._favorite_numbers_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.favorite_numbers, base, endianSwap);
    for (uint32_t i = 0; i < v._favorite_numbers_count; ++i)
        DoEndianSwapAndPointerFixup(v.favorite_numbers.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._inventory_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.inventory, base, endianSwap);
    for (uint32_t i = 0; i < v._inventory_count; ++i)
        DoEndianSwapAndPointerFixup(v.inventory.ptr[i], base, endianSwap);
}
