/*
* This code was generated by df_game_data https://github.com/Atrix256/df_game_data
* Do not edit manually, unless you understand the consequences.
*/

#pragma once

#include <stdint.h>
#include <stdio.h>
#include <cstring>

class dfgd
{
public:
    ~dfgd();

    // Note: the memory will be modified, and it must stay around for the life of the object.
    bool LoadFromMemory(void* mem, uint32_t size);

    bool LoadFromFile(const char* fileName);

public:
    template <typename T>
    union Ptr64
    {
        T* ptr;
        uint64_t _64 = 0;

        void Set(void* base, uint64_t offset)
        {
            _64 = reinterpret_cast<uintptr_t>(base) + offset;
        }
    };

    struct Bool
    {
        uint8_t _8 = 0;
        bool Get() const
        {
            return _8 != 0;
        }
    };

    #pragma pack(push, 1)

    enum class EyeColor : uint16_t
    {
        Brown,
        Hazel,
        Blue,
        Green,
    };

    enum class Alignment : uint16_t
    {
        Good,
        Neutral,
        Evil,
    };

    enum class Class : uint16_t
    {
        Warrior,
        Wizard,
        Cleric,
        Druid,
    };

    struct Vec3
    {
        float x;
        float y;
        float z;
    };

    struct Item
    {
        Ptr64<char> name;
    };

    struct Character
    {
        Ptr64<char> name;
        EyeColor eyeColor;
        Alignment alignment;
        Class playerClass;
        Vec3 location;
        uint16_t max_hp;
        uint16_t max_mp;
        Bool playable;
        uint32_t _favorite_numbers_count = 0;
        uint64_t favorite_numbers;
        uint32_t _inventory_count = 0;
        uint64_t inventory;
    };

    #pragma pack(pop)

private:
    template <typename T>
    static bool Read(T& value, void* mem, uint32_t& memIndex, uint32_t memSize)
    {
        if (memSize - memIndex < sizeof(T))
            return false;

        memcpy(&value, &((char*)mem)[memIndex], sizeof(value));
        memIndex += sizeof(value);

        return true;
    }

    void DoEndianSwap();

    template <typename T>
    inline static void DoPointerFixup(T& v, void* base)
    {
    }

    template <typename T>
    inline static void DoPointerFixup(T*& v, void* base)
    {
        v = reinterpret_cast<T*>(reinterpret_cast<uintptr_t>(base) + reinterpret_cast<uintptr_t>(v));
    }

    template <typename T>
    inline static void DoPointerFixup(Ptr64<T>& v, void* base)
    {
        v._64 += reinterpret_cast<uintptr_t>(base);
    }

    static void DoPointerFixup(Vec3& v, void* base);
    static void DoPointerFixup(Item& v, void* base);
    static void DoPointerFixup(Character& v, void* base);

private:
    uint8_t* m_ownedMemory = nullptr;

public:
    uint32_t m_table_Character_count = 0;
    Ptr64<char*> m_table_Character_names;
    Ptr64<Character> m_table_Character;

    uint32_t m_table_Item_count = 0;
    Ptr64<char*> m_table_Item_names;
    Ptr64<Item> m_table_Item;

};

// ================================= Misc =================================

dfgd::~dfgd()
{
    delete[] m_ownedMemory;
    m_ownedMemory = nullptr;
}

inline constexpr uint32_t MakeFourCC(char a, char b, char c, char d)
{
    return (uint32_t)(uint8_t)a
        | ((uint32_t)(uint8_t)b << 8)
        | ((uint32_t)(uint8_t)c << 16)
        | ((uint32_t)(uint8_t)d << 24);
}

// ================================= LOADING =================================

bool dfgd::LoadFromMemory(void* mem, uint32_t memSize)
{
    uint32_t memIndex = 0;

    // verify fourcc, and do endian swap if we need to
    {
        static const uint32_t fourcc_regular = MakeFourCC('D', 'F', 'G', 'D');
        static const uint32_t fourcc_swapped = MakeFourCC('D', 'G', 'F', 'D'); // TODO: make this by endian swapping fourcc_regular
        uint32_t fourcc = 0;
        if (!Read(fourcc, mem, memIndex, memSize))
            return false;

        if (fourcc == fourcc_swapped)
            DoEndianSwap();
        else if (fourcc != fourcc_regular)
            return false;
    }

    // Verify that the schema hash in the binary data matches the schema hash this file was made for
    {
        uint64_t hash = 0;
        if (!Read(hash, mem, memIndex, memSize) || hash != 0x4d6fca5bde6206b2ULL)
            return false;
    }
    // Character Table
    {
        if (!Read(m_table_Character_count, mem, memIndex, memSize))
            return false;

        if (m_table_Character_count > 0)
        {
            // get char** to LUT and fixup string pointers
            if (memSize - memIndex < m_table_Character_count * sizeof(uint64_t))
                return false;
            m_table_Character_names.Set(mem, memIndex);
            for (uint32_t i = 0; i < m_table_Character_count; ++i)
                DoPointerFixup(m_table_Character_names.ptr[i], mem);
            memIndex += m_table_Character_count * sizeof(uint64_t);

            // Get a pointer to the first entry in the table
            if (memSize - memIndex < m_table_Character_count * sizeof(Character))
                return false;
            m_table_Character.Set(mem, memIndex);
            memIndex += m_table_Character_count * sizeof(Character);

            // Do pointer fixup
            for (uint32_t i = 0; i < m_table_Character_count; ++i)
                DoPointerFixup(m_table_Character.ptr[i], mem);
        }
    }

    // Item Table
    {
        if (!Read(m_table_Item_count, mem, memIndex, memSize))
            return false;

        if (m_table_Item_count > 0)
        {
            // get char** to LUT and fixup string pointers
            if (memSize - memIndex < m_table_Item_count * sizeof(uint64_t))
                return false;
            m_table_Item_names.Set(mem, memIndex);
            for (uint32_t i = 0; i < m_table_Item_count; ++i)
                DoPointerFixup(m_table_Item_names.ptr[i], mem);
            memIndex += m_table_Item_count * sizeof(uint64_t);

            // Get a pointer to the first entry in the table
            if (memSize - memIndex < m_table_Item_count * sizeof(Item))
                return false;
            m_table_Item.Set(mem, memIndex);
            memIndex += m_table_Item_count * sizeof(Item);

            // Do pointer fixup
            for (uint32_t i = 0; i < m_table_Item_count; ++i)
                DoPointerFixup(m_table_Item.ptr[i], mem);
        }
    }

    return true;
}

bool dfgd::LoadFromFile(const char* fileName)
{
    FILE* file = nullptr;
    fopen_s(&file, fileName, "rb");
    if (!file)
        return false;

    fseek(file, 0, SEEK_END);
    uint32_t fileSize = (uint32_t)ftell(file);

    m_ownedMemory = new uint8_t[fileSize];
    fseek(file, 0, SEEK_SET);

    if (fread(m_ownedMemory, fileSize, 1, file) != 1)
        return false;

    fclose(file);

    bool ret = LoadFromMemory(m_ownedMemory, fileSize);

    return ret;
}

// ================================= Pointer Fixup =================================

void dfgd::DoPointerFixup(dfgd::Vec3& v, void* base)
{
    DoPointerFixup(v.x, base);
    DoPointerFixup(v.y, base);
    DoPointerFixup(v.z, base);
}

void dfgd::DoPointerFixup(dfgd::Item& v, void* base)
{
    DoPointerFixup(v.name, base);
}

void dfgd::DoPointerFixup(dfgd::Character& v, void* base)
{
    DoPointerFixup(v.name, base);
    DoPointerFixup(v.eyeColor, base);
    DoPointerFixup(v.alignment, base);
    DoPointerFixup(v.playerClass, base);
    DoPointerFixup(v.location, base);
    DoPointerFixup(v.max_hp, base);
    DoPointerFixup(v.max_mp, base);
    DoPointerFixup(v.playable, base);
    DoPointerFixup(v.favorite_numbers, base);
    DoPointerFixup(v.inventory, base);
}

// ================================= Endian Swap =================================

// TODO: this
void dfgd::DoEndianSwap()
{/*DoEndianSwap*/
}
