/*
* This code was generated by df_game_data https://github.com/Atrix256/df_game_data
* Do not edit manually, unless you understand the consequences.
*
* To load data, call either of these functions:
*
* bool LoadFromMemory(void* mem, uint32_t size);
* bool LoadFromFile(const char* fileName);
*
* To get data entries after loading, there are functions like below, assuming "Item"
* is the table you want to get an entry from:
*
* uint32 GetItemCount();                - Get the number of items
* ItemRecord GetItem(uint32_t index);   - Get item by index
* ItemRecord GetItem(const char* name); - Get item by name, if entry name look up table enabled in settings
*
* There are also templated functions of this form:
*
* uint32 GetCount<T>()
* Record<T> Get<T>(uint32_t index)
* Record<T> Get<T>(const char* name)
*
* For hot reloading, call Tick() periodically to check if the bin file on disk has changed.
* If it has changed, Tick() will return true after reloading the data file.
*
* Record objects will start pointing at the new data when used. They will find the
* record which has the same name in the new data.
*/
// Made with df_game_data version 1.0.1

#pragma once

#include <stdint.h>
#include <stdio.h>
#include <cstring>
#include <algorithm>
#include <filesystem>

class Data
{
public:
    ~Data();

    // Note: the memory will be modified, and it must stay around for the life of the object.
    bool LoadFromMemory(void* mem, uint32_t size);

    bool LoadFromFile(const char* fileName);

public:
    #pragma pack(push, 1)

    template <typename T>
    union Ptr64
    {
        T* ptr;
        uint64_t _64 = 0;
    };

    struct Bool
    {
        uint8_t _8 = 0;
        bool Get() const
        {
            return _8 != 0;
        }
    };

    #pragma pack(pop)

    template <typename T>
    struct Record
    {
    public:
        Record()
        {
        }

        Record(const Record& other)
        {
            m_record = other.m_record;
            m_parent = other.m_parent;
            m_generation = other.m_generation;
            size_t nameLen = strlen(other.m_recordName);
            m_recordName = new char[nameLen + 1];
            memcpy(m_recordName, other.m_recordName, nameLen+1);
        }

        Record(Record&& other) noexcept
        {
            std::swap(m_record, other.m_record);
            std::swap(m_parent, other.m_parent);
            std::swap(m_generation, other.m_generation);
            std::swap(m_recordName, other.m_recordName);
        }

        ~Record()
        {
            if (m_recordName)
            {
                delete[] m_recordName;
                m_recordName = nullptr;
            }
        }

        Record& operator=(Record other)
        {
            std::swap(m_record, other.m_record);
            std::swap(m_parent, other.m_parent);
            std::swap(m_generation, other.m_generation);
            std::swap(m_recordName, other.m_recordName);
            return *this;
        }

        const T& Get()
        {
            if (m_parent && m_parent->m_generation != m_generation)
                *this = m_parent->Get<T>(m_recordName);
            static const T s_dummy = T();
            return m_record ? *m_record : s_dummy;
        }

        bool Valid() const
        {
            Get();
            return m_record != nullptr;
        }

    private:
        friend class Data;
        T* m_record = nullptr;

        const Data* m_parent = nullptr;
        uint32_t m_generation = ~0;
        char* m_recordName = nullptr;
    };

public:
    #pragma pack(push, 1)
    struct Item
    {
        Ptr64<char> name;
        float value;
    };

    using ItemRecord = Record<Item>;

    struct Character
    {
        Ptr64<char> name;
        uint32_t inventory_count = 0;
        Ptr64<Ptr64<Item>> inventory;
    };

    using CharacterRecord = Record<Character>;

    #pragma pack(pop)

private:
    template <typename T>
    inline static void EndianSwap(T& v)
    {
        uint8_t* bytes = reinterpret_cast<uint8_t*>(&v);
        for (size_t i = 0; i < sizeof(T) / 2; ++i)
        {
            uint8_t tmp = bytes[i];
            bytes[i] = bytes[sizeof(T) - 1 - i];
            bytes[sizeof(T) - 1 - i] = tmp;
        }
    }

    template <typename T>
    static bool Read(T& value, void* mem, uint32_t& memIndex, uint32_t memSize, bool endianSwap)
    {
        if (memSize - memIndex < sizeof(value))
            return false;

        memcpy(&value, &((char*)mem)[memIndex], sizeof(value));
        memIndex += sizeof(value);

        if (endianSwap)
            EndianSwap(value);

        return true;
    }

private:
    // From https://jcgt.org/published/0009/03/02/
    // supplemental material uint pcg(uint v)
    static inline uint32_t pcg_hash(uint32_t input)
    {
        uint32_t state = input * 747796405u + 2891336453u;
        uint32_t word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
        return (word >> 22u) ^ word;
    }

private:
    template <typename T>
    inline static void DoPointerFixup(T& v, void* base)
    {
    }

    template <typename T>
    inline static void DoPointerFixup(T*& v, void* base)
    {
        v = reinterpret_cast<T*>(reinterpret_cast<uintptr_t>(base) + reinterpret_cast<uintptr_t>(v));
    }

    template <typename T>
    inline static void DoPointerFixup(Ptr64<T>& v, void* base)
    {
        // null ptrs are preserved.
        if (v._64 == 0)
            return;
        v._64 += reinterpret_cast<uintptr_t>(base);
    }

private:
    template <typename T>
    inline static void DoEndianSwapAndPointerFixup(T& v, void* base, bool endianSwap)
    {
        if (endianSwap)
            EndianSwap(v);
        DoPointerFixup(v, base);
    }

    static void DoEndianSwapAndPointerFixup(Item& v, void* base, bool endianSwap);
    static void DoEndianSwapAndPointerFixup(Character& v, void* base, bool endianSwap);

private:
    uint8_t* m_ownedMemory = nullptr;

public:
    // Returns whether the data was updated or not (hot reloading).
    bool Tick()
    {
        std::filesystem::file_time_type fileTime = std::filesystem::last_write_time(m_fileName);
        if (fileTime > m_fileTime)
        {
            LoadFromFile(m_fileName);
            return true;
        }

        return false;
    }

    template <typename T>
    inline uint32_t GetCount() const;

    template <typename T>
    inline Record<T> Get(uint32_t index) const;

    // An int version to catch index 0 not being ambiguous with nullptr
    template <typename T>
    inline Record<T> Get(int index) const
    {
        return Get((uint32_t)index);
    }

    template <typename T>
    inline Record<T> Get(const char* name) const;

    inline uint32_t GetItemCount() const;
    inline ItemRecord GetItem(uint32_t index) const;
    inline ItemRecord GetItem(int index) const
    {
        // An int version to catch index 0 not being ambiguous with nullptr
        return GetItem((uint32_t)index);
    }
    inline ItemRecord GetItem(const char* name) const;

    inline uint32_t GetCharacterCount() const;
    inline CharacterRecord GetCharacter(uint32_t index) const;
    inline CharacterRecord GetCharacter(int index) const
    {
        // An int version to catch index 0 not being ambiguous with nullptr
        return GetCharacter((uint32_t)index);
    }
    inline CharacterRecord GetCharacter(const char* name) const;

private:
    // Incremented each time the data is reloaded
    uint32_t m_generation = 0;

    // The last modification time of the file, for hot reloading.
    std::filesystem::file_time_type m_fileTime;

    // The filename so we can get its file time again later.
    char* m_fileName = nullptr;

    uint32_t m_table_Character_count = 0;
    Ptr64<Ptr64<char>> m_table_Character_names;
    Ptr64<Character> m_table_Character;

    uint32_t m_table_Item_count = 0;
    Ptr64<Ptr64<char>> m_table_Item_names;
    Ptr64<Item> m_table_Item;
};

// ================================= Misc =================================

inline Data::~Data()
{
    delete[] m_ownedMemory;
    m_ownedMemory = nullptr;
    if (m_fileName != nullptr)
    {
        delete[] m_fileName;
        m_fileName = nullptr;
    }
}

// ================================= LOADING =================================

inline bool Data::LoadFromMemory(void* mem, uint32_t memSize)
{
    auto MakeFourCC = [](char a, char b, char c, char d) -> uint32_t
    {
        return (uint32_t)(uint8_t)a
            | ((uint32_t)(uint8_t)b << 8)
            | ((uint32_t)(uint8_t)c << 16)
            | ((uint32_t)(uint8_t)d << 24);
    };

    uint32_t memIndex = 0;

    // verify fourcc, and see if we need to do endian swaps
    bool endianSwap = false;
    {
        static const uint32_t fourcc_regular = MakeFourCC('D', 'F', 'G', 'D');
        static const uint32_t fourcc_swapped = MakeFourCC('D', 'G', 'F', 'D');

        uint32_t fourcc = 0;
        if (!Read(fourcc, mem, memIndex, memSize, false))
            return false;

        if (fourcc == fourcc_swapped)
            endianSwap = true;
        else if (fourcc != fourcc_regular)
            return false;
    }

    // Read the version number the binary file was made with.
    // Unused now, but can be used for backwards compatibility etc later.
    {
        uint8_t version[3];
        if (!Read(version[0], mem, memIndex, memSize, endianSwap) ||
            !Read(version[1], mem, memIndex, memSize, endianSwap) ||
            !Read(version[2], mem, memIndex, memSize, endianSwap))
        {
            return false;
        }
    }

    // De obfuscate the data
    {
        size_t contentStart = 7; // start after the fourcc and the 3 byte version
        size_t bytesRemaining = memSize - contentStart;
        uint32_t rng = pcg_hash(0x1337beef);
        uint8_t* data = &((uint8_t*)mem)[contentStart];
        while (bytesRemaining > 0)
        {
            rng = pcg_hash(rng);

            for (size_t i = 0; i < ((bytesRemaining < 4) ? bytesRemaining : 4); ++i)
                data[i] = data[i] ^ ((uint8_t*)&rng)[i];

            data += 4;

            if (bytesRemaining >= 4)
                bytesRemaining -= 4;
            else
                bytesRemaining = 0;
        }
    }

    // Verify that the schema hash in the binary data matches the schema hash this file was made for
    {
        uint64_t hash = 0;
        if (!Read(hash, mem, memIndex, memSize, endianSwap) || hash != 0x501731d4718c3923ULL)
            return false;
    }

    // Character Table
    {
        if (!Read(m_table_Character_count, mem, memIndex, memSize, endianSwap))
            return false;

        if (m_table_Character_count > 0)
        {
            // get char** to LUT and fixup string pointers
            if (memSize - memIndex < m_table_Character_count * sizeof(uint64_t))
                return false;
            m_table_Character_names._64 = memIndex;
            DoEndianSwapAndPointerFixup(m_table_Character_names, mem, endianSwap);
            for (uint32_t i = 0; i < m_table_Character_count; ++i)
                DoEndianSwapAndPointerFixup(m_table_Character_names.ptr[i], mem, endianSwap);
            memIndex += m_table_Character_count * sizeof(uint64_t);

            // Get a pointer to the first entry in the table
            if (memSize - memIndex < m_table_Character_count * sizeof(Character))
                return false;
            m_table_Character._64 = memIndex;
            DoEndianSwapAndPointerFixup(m_table_Character, mem, endianSwap);
            memIndex += m_table_Character_count * sizeof(Character);

            // Do pointer fixup
            for (uint32_t i = 0; i < m_table_Character_count; ++i)
                DoEndianSwapAndPointerFixup(m_table_Character.ptr[i], mem, endianSwap);
        }
    }

    // Item Table
    {
        if (!Read(m_table_Item_count, mem, memIndex, memSize, endianSwap))
            return false;

        if (m_table_Item_count > 0)
        {
            // get char** to LUT and fixup string pointers
            if (memSize - memIndex < m_table_Item_count * sizeof(uint64_t))
                return false;
            m_table_Item_names._64 = memIndex;
            DoEndianSwapAndPointerFixup(m_table_Item_names, mem, endianSwap);
            for (uint32_t i = 0; i < m_table_Item_count; ++i)
                DoEndianSwapAndPointerFixup(m_table_Item_names.ptr[i], mem, endianSwap);
            memIndex += m_table_Item_count * sizeof(uint64_t);

            // Get a pointer to the first entry in the table
            if (memSize - memIndex < m_table_Item_count * sizeof(Item))
                return false;
            m_table_Item._64 = memIndex;
            DoEndianSwapAndPointerFixup(m_table_Item, mem, endianSwap);
            memIndex += m_table_Item_count * sizeof(Item);

            // Do pointer fixup
            for (uint32_t i = 0; i < m_table_Item_count; ++i)
                DoEndianSwapAndPointerFixup(m_table_Item.ptr[i], mem, endianSwap);
        }
    }

    // Track that the data was (re)loaded to invalidate stale records
    m_generation++;

    return true;
}

inline bool Data::LoadFromFile(const char* fileName)
{
    FILE* file = nullptr;
    fopen_s(&file, fileName, "rb");
    if (!file)
        return false;

    fseek(file, 0, SEEK_END);
    uint32_t fileSize = (uint32_t)ftell(file);

    m_ownedMemory = new uint8_t[fileSize];
    fseek(file, 0, SEEK_SET);

    if (fread(m_ownedMemory, fileSize, 1, file) != 1)
        return false;

    fclose(file);

    bool ret = LoadFromMemory(m_ownedMemory, fileSize);

    // Save off the file name and get the file time, for hot reloading
    if (!m_fileName || strcmp(m_fileName, fileName))
    {
        if (m_fileName)
            delete[] m_fileName;
        size_t fileNameLen = strlen(fileName);
        m_fileName = new char[fileNameLen + 1];
        memcpy(m_fileName, fileName, fileNameLen + 1);
    }
    m_fileTime = std::filesystem::last_write_time(m_fileName);

    return ret;
}

// ================================= Pointer Fixup =================================

inline void Data::DoEndianSwapAndPointerFixup(Item& v, void* base, bool endianSwap)
{
    DoEndianSwapAndPointerFixup(v.name, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.value, base, endianSwap);
}

inline void Data::DoEndianSwapAndPointerFixup(Character& v, void* base, bool endianSwap)
{
    DoEndianSwapAndPointerFixup(v.name, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.inventory_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.inventory, base, endianSwap);
    for (uint32_t i = 0; i < v.inventory_count; ++i)
        DoEndianSwapAndPointerFixup(v.inventory.ptr[i], base, endianSwap);
}

// ================================= Public Interface =================================
template <>
inline uint32_t Data::GetCount<Data::Character>() const
{
    return m_table_Character_count;
}

template <>
inline Data::CharacterRecord Data::Get<Data::Character>(uint32_t index) const
{
    CharacterRecord ret;
    if (index < m_table_Character_count)
    {
        ret.m_record = &m_table_Character.ptr[index];
        size_t nameLen = strlen(m_table_Character_names.ptr[index].ptr);
        ret.m_recordName = new char[nameLen + 1];
        memcpy(ret.m_recordName, m_table_Character_names.ptr[index].ptr, nameLen + 1);
    }

    ret.m_parent = this;
    ret.m_generation = m_generation;

    return ret;
}

template <>
inline Data::CharacterRecord Data::Get<Data::Character>(const char* name) const
{
    CharacterRecord ret;

    Ptr64<char>* array = m_table_Character_names.ptr;
    const uint32_t count = m_table_Character_count;

    auto it = std::lower_bound(
        array,
        array + count,
        name,
        [](const Ptr64<char>& item, const char* val)
        {
            return strcmp(item.ptr, val) < 0;
        }
    );

    uint32_t index = uint32_t(it - array);

    if (index < count && !strcmp(it->ptr, name))
    {
        ret.m_record = &m_table_Character.ptr[index];
        size_t nameLen = strlen(m_table_Character_names.ptr[index].ptr);
        ret.m_recordName = new char[nameLen + 1];
        memcpy(ret.m_recordName, m_table_Character_names.ptr[index].ptr, nameLen + 1);
    }

    ret.m_parent = this;
    ret.m_generation = m_generation;

    return ret;
}

inline uint32_t Data::GetCharacterCount() const
{
    return GetCount<Character>();
}

inline Data::CharacterRecord Data::GetCharacter(uint32_t index) const
{
    return Get<Character>(index);
}

inline Data::CharacterRecord Data::GetCharacter(const char* name) const
{
    return Get<Character>(name);
}

template <>
inline uint32_t Data::GetCount<Data::Item>() const
{
    return m_table_Item_count;
}

template <>
inline Data::ItemRecord Data::Get<Data::Item>(uint32_t index) const
{
    ItemRecord ret;
    if (index < m_table_Item_count)
    {
        ret.m_record = &m_table_Item.ptr[index];
        size_t nameLen = strlen(m_table_Item_names.ptr[index].ptr);
        ret.m_recordName = new char[nameLen + 1];
        memcpy(ret.m_recordName, m_table_Item_names.ptr[index].ptr, nameLen + 1);
    }

    ret.m_parent = this;
    ret.m_generation = m_generation;

    return ret;
}

template <>
inline Data::ItemRecord Data::Get<Data::Item>(const char* name) const
{
    ItemRecord ret;

    Ptr64<char>* array = m_table_Item_names.ptr;
    const uint32_t count = m_table_Item_count;

    auto it = std::lower_bound(
        array,
        array + count,
        name,
        [](const Ptr64<char>& item, const char* val)
        {
            return strcmp(item.ptr, val) < 0;
        }
    );

    uint32_t index = uint32_t(it - array);

    if (index < count && !strcmp(it->ptr, name))
    {
        ret.m_record = &m_table_Item.ptr[index];
        size_t nameLen = strlen(m_table_Item_names.ptr[index].ptr);
        ret.m_recordName = new char[nameLen + 1];
        memcpy(ret.m_recordName, m_table_Item_names.ptr[index].ptr, nameLen + 1);
    }

    ret.m_parent = this;
    ret.m_generation = m_generation;

    return ret;
}

inline uint32_t Data::GetItemCount() const
{
    return GetCount<Item>();
}

inline Data::ItemRecord Data::GetItem(uint32_t index) const
{
    return Get<Item>(index);
}

inline Data::ItemRecord Data::GetItem(const char* name) const
{
    return Get<Item>(name);
}
