/*
This code was generated by df_game_data https://github.com/Atrix256/df_game_data
Do not edit manually, unless you understand the consequences.

    Do this:
        #define DF_GAMEDATA_IMPLEMENTATION
    before you include this file in *one* C or C++ file to create the implementation.

To use:

    InitDatabase()    - Initialize a database object. must be called before loading.
    DestroyDatabase() - Destroys a database object and frees any internal memory used.
    LoadFromMemory()  - Loads a database from a bin file in memory.
    LoadFromFile()    - Loads a database from a bin file on disk.
    Tick()            - Used for hot reloading. Returns true when hot reload happens, so you can update cached data.
    StringIndex()     - Returns the index of a record, given a name table and a name.

*/
// Made with df_game_data version 1.0.1

#pragma once

#include <stdint.h>
#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

#pragma pack(push, 1)
typedef struct ShopData_C_Item
{
    uint64_t name;
    uint32_t sellCost;
    uint32_t buyCost;
} ShopData_C_Item;
#pragma pack(pop)

typedef struct ShopData_C_Database
{
    uint8_t* ownedMemory;

    uint32_t table_Item_count;
    uint64_t table_Item_names; // char**
    uint64_t table_Item;       // ShopData_C_Item*
} ShopData_C_Database;

// Public interface
void ShopData_C_InitDatabase(ShopData_C_Database* db);
void ShopData_C_DestroyDatabase(ShopData_C_Database* db);
bool ShopData_C_LoadFromMemory(void* mem, uint32_t size, ShopData_C_Database* db);
bool ShopData_C_LoadFromFile(const char* fileName, ShopData_C_Database* db);
bool ShopData_C_Tick(ShopData_C_Database* db);
size_t ShopData_C_StringIndex(const char** arr, size_t count, const char* key);

// Private implementation
#ifdef DF_GAMEDATA_IMPLEMENTATION

// From https://jcgt.org/published/0009/03/02/
// supplemental material uint pcg(uint v)
uint32_t ShopData_C_pcg_hash(uint32_t input)
{
    uint32_t state = input * 747796405u + 2891336453u;
    uint32_t word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}

int ShopData_C_CompareKeyToElement(const void* key, const void* elem)
{
    return strcmp((const char*)key, *(const char* const*)elem);
}

// Returns count if not found
size_t ShopData_C_StringIndex(const char** arr, size_t count, const char* key)
{
    char** hit = bsearch(key, arr, count, sizeof(const char*), ShopData_C_CompareKeyToElement);
    return hit ? (hit - arr) : count;
}

void ShopData_C_EndianSwap_U8(uint8_t* value)
{
    (void)value;
}

void ShopData_C_EndianSwap_U16(uint16_t* value)
{
    *value = ((*value & 0x00FF) << 8) |
             ((*value & 0xFF00) >> 8);
}

void ShopData_C_EndianSwap_U32(uint32_t* value)
{
    *value = ((*value & 0x000000FF) << 24) |
             ((*value & 0x0000FF00) << 8) |
             ((*value & 0x00FF0000) >> 8) |
             ((*value & 0xFF000000) >> 24);
}

void ShopData_C_EndianSwap_U64(uint64_t* value)
{
    *value = ((*value & 0x00000000000000FFULL) << 56) |
        ((*value & 0x000000000000FF00ULL) << 40) |
        ((*value & 0x0000000000FF0000ULL) << 24) |
        ((*value & 0x00000000FF000000ULL) << 8) |
        ((*value & 0x000000FF00000000ULL) >> 8) |
        ((*value & 0x0000FF0000000000ULL) >> 24) |
        ((*value & 0x00FF000000000000ULL) >> 40) |
        ((*value & 0xFF00000000000000ULL) >> 56);
}

bool ShopData_C_Read_U8(uint8_t* value, void* mem, uint32_t* memIndex, uint32_t memSize, bool endianSwap)
{
    if (memSize - *memIndex < sizeof(*value))
        return false;

    memcpy(value, &((uint8_t*)mem)[*memIndex], sizeof(*value));
    *memIndex += sizeof(*value);

    if (endianSwap)
        ShopData_C_EndianSwap_U8(value);

    return true;
}

bool ShopData_C_Read_U16(uint16_t* value, void* mem, uint32_t* memIndex, uint32_t memSize, bool endianSwap)
{
    if (memSize - *memIndex < sizeof(*value))
        return false;

    memcpy(value, &((uint8_t*)mem)[*memIndex], sizeof(*value));
    *memIndex += sizeof(*value);

    if (endianSwap)
        ShopData_C_EndianSwap_U16(value);

    return true;
}

bool ShopData_C_Read_U32(uint32_t* value, void* mem, uint32_t* memIndex, uint32_t memSize, bool endianSwap)
{
    if (memSize - *memIndex < sizeof(*value))
        return false;

    memcpy(value, &((uint8_t*)mem)[*memIndex], sizeof(*value));
    *memIndex += sizeof(*value);

    if (endianSwap)
        ShopData_C_EndianSwap_U32(value);

    return true;
}

bool ShopData_C_Read_U64(uint64_t* value, void* mem, uint32_t* memIndex, uint32_t memSize, bool endianSwap)
{
    if (memSize - *memIndex < sizeof(*value))
        return false;

    memcpy(value, &((uint8_t*)mem)[*memIndex], sizeof(*value));
    *memIndex += sizeof(*value);

    if (endianSwap)
        ShopData_C_EndianSwap_U64(value);

    return true;
}

void ShopData_C_DoEndianSwapAndPointerFixup_U8(uint8_t* value, void* mem, bool endianSwap)
{
    if (endianSwap)
        ShopData_C_EndianSwap_U8(value);
}

void ShopData_C_DoEndianSwapAndPointerFixup_U16(uint16_t* value, void* mem, bool endianSwap)
{
    if (endianSwap)
        ShopData_C_EndianSwap_U16(value);
}

void ShopData_C_DoEndianSwapAndPointerFixup_U32(uint32_t* value, void* mem, bool endianSwap)
{
    if (endianSwap)
        ShopData_C_EndianSwap_U32(value);
}

void ShopData_C_DoEndianSwapAndPointerFixup_U64(uint64_t* value, void* mem, bool endianSwap)
{
    if (endianSwap)
        ShopData_C_EndianSwap_U64(value);
}

void ShopData_C_DoEndianSwapAndPointerFixup_float(float* value, void* mem, bool endianSwap)
{
    if (endianSwap)
        ShopData_C_EndianSwap_U32((uint32_t*)value);
}

void ShopData_C_DoEndianSwapAndPointerFixup_double(double* value, void* mem, bool endianSwap)
{
    if (endianSwap)
        ShopData_C_EndianSwap_U64((uint64_t*)value);
}

void ShopData_C_DoEndianSwapAndPointerFixup_Ptr(uint64_t* value, void* mem, bool endianSwap)
{
    if (endianSwap)
        ShopData_C_EndianSwap_U64(value);
    if (*value != 0)
        *value += (uint64_t)mem;
}

void ShopData_C_DoEndianSwapAndPointerFixup_Item(ShopData_C_Item* value, void* mem, bool endianSwap)
{
    ShopData_C_DoEndianSwapAndPointerFixup_Ptr(&value->name, mem, endianSwap);
    ShopData_C_DoEndianSwapAndPointerFixup_U32(&value->sellCost, mem, endianSwap);
    ShopData_C_DoEndianSwapAndPointerFixup_U32(&value->buyCost, mem, endianSwap);
}

void ShopData_C_InitDatabase(ShopData_C_Database* db)
{
    db->ownedMemory = NULL;
    db->table_Item_count = 0;
}

void ShopData_C_DestroyDatabase(ShopData_C_Database* db)
{
    if (db->ownedMemory)
    {
        free(db->ownedMemory);
        db->ownedMemory = NULL;
    }
}

bool ShopData_C_LoadFromMemory(void* mem, uint32_t memSize, ShopData_C_Database* db)
{
    #define MAKE_FOUR_CC(A, B, C, D) \
        ( (uint32_t)(uint8_t)A \
        | ((uint32_t)(uint8_t)B << 8) \
        | ((uint32_t)(uint8_t)C << 16) \
        | ((uint32_t)(uint8_t)D << 24))

    uint32_t memIndex = 0;

    // verify fourcc, and see if we need to do endian swaps
    bool endianSwap = false;
    {
        static const uint32_t fourcc_regular = MAKE_FOUR_CC('D', 'F', 'G', 'D');
        static const uint32_t fourcc_swapped = MAKE_FOUR_CC('D', 'G', 'F', 'D');

        uint32_t fourcc = 0;
        if (!ShopData_C_Read_U32(&fourcc, mem, &memIndex, memSize, false))
            return false;

        if (fourcc == fourcc_swapped)
            endianSwap = true;
        else if (fourcc != fourcc_regular)
            return false;
    }

    // Read the version number the binary file was made with.
    // Unused now, but can be used for backwards compatibility etc later.
    {
        uint8_t version[3];
        if (!ShopData_C_Read_U8(&version[0], mem, &memIndex, memSize, endianSwap) ||
            !ShopData_C_Read_U8(&version[1], mem, &memIndex, memSize, endianSwap) ||
            !ShopData_C_Read_U8(&version[2], mem, &memIndex, memSize, endianSwap))
        {
            return false;
        }
    }

    // De obfuscate the data
    {
        size_t contentStart = 7; // start after the fourcc and the 3 byte version
        size_t bytesRemaining = memSize - contentStart;
        uint32_t rng = ShopData_C_pcg_hash(0x1337beef);
        uint8_t* data = &((uint8_t*)mem)[contentStart];
        while (bytesRemaining > 0)
        {
            rng = ShopData_C_pcg_hash(rng);

            for (size_t i = 0; i < ((bytesRemaining < 4) ? bytesRemaining : 4); ++i)
                data[i] = data[i] ^ ((uint8_t*)&rng)[i];

            data += 4;

            if (bytesRemaining >= 4)
                bytesRemaining -= 4;
            else
                bytesRemaining = 0;
        }
    }

    // Verify that the schema hash in the binary data matches the schema hash this file was made for
    {
        uint64_t hash = 0;
        if (!ShopData_C_Read_U64(&hash, mem, &memIndex, memSize, endianSwap) || hash != 0x8d4eff8cb605d210ULL)
            return false;
    }

    // Item Table
    {
        if (!ShopData_C_Read_U32(&db->table_Item_count, mem, &memIndex, memSize, endianSwap))
            return false;

        if (db->table_Item_count > 0)
        {
            // get char** to LUT and fixup string pointers
            if (memSize - memIndex < db->table_Item_count * sizeof(uint64_t))
                return false;
            db->table_Item_names = memIndex;
            ShopData_C_DoEndianSwapAndPointerFixup_Ptr(&db->table_Item_names, mem, endianSwap);
            for (uint32_t i = 0; i < db->table_Item_count; ++i)
                ShopData_C_DoEndianSwapAndPointerFixup_Ptr(&((uint64_t*)db->table_Item_names)[i], mem, endianSwap);
            memIndex += db->table_Item_count * sizeof(uint64_t);

            // Get a pointer to the first entry in the table
            if (memSize - memIndex < db->table_Item_count * sizeof(ShopData_C_Item))
                return false;
            db->table_Item = memIndex;
            ShopData_C_DoEndianSwapAndPointerFixup_Ptr(&db->table_Item, mem, endianSwap);
            memIndex += db->table_Item_count * sizeof(ShopData_C_Item);

            // Do pointer fixup
            for (uint32_t i = 0; i < db->table_Item_count; ++i)
                ShopData_C_DoEndianSwapAndPointerFixup_Item(&((ShopData_C_Item*)db->table_Item)[i], mem, endianSwap);
        }
    }

    return true;
}

bool ShopData_C_LoadFromFile(const char* fileName, ShopData_C_Database* db)
{
    FILE* file = NULL;
    fopen_s(&file, fileName, "rb");
    if (!file)
        return false;

    fseek(file, 0, SEEK_END);
    uint32_t fileSize = (uint32_t)ftell(file);

    if (db->ownedMemory)
        free(db->ownedMemory);

    db->ownedMemory = malloc(fileSize);
    fseek(file, 0, SEEK_SET);

    if (fread(db->ownedMemory, fileSize, 1, file) != 1)
        return false;

    fclose(file);

    bool ret = ShopData_C_LoadFromMemory(db->ownedMemory, fileSize, db);

    return ret;
}

bool ShopData_C_Tick(ShopData_C_Database* db)
{
    return false;
}
#endif

/*
TODO:
* document how to use it at the top, like we do the C++ interface
* document hot reloading: tick returns true, then you need to update anything you cached.
*/
