/*
* This code was generated by df_game_data https://github.com/Atrix256/df_game_data
* Do not edit manually, unless you understand the consequences.
*
* To load data, call either of these functions:
*
* bool LoadFromMemory(void* mem, uint32_t size);
* bool LoadFromFile(const char* fileName);
*
* To get data entries after loading, there are functions like below, assuming "Item"
* is the table you want to get an entry from:
*
* uint32 GetItemCount();                - Get the number of items
* ItemRecord GetItem(uint32_t index);   - Get item by index
* ItemRecord GetItem(const char* name); - Get item by name, if entry name look up table enabled in settings
*
* There are also templated functions of this form:
*
* uint32 GetCount<T>()
* Record<T> Get<T>(uint32_t index)
* Record<T> Get<T>(const char* name)
*
* For hot reloading, call Tick() periodically to check if the bin file on disk has changed.
* If it has changed, Tick() will return true after reloading the data file.
*
* Record objects will start pointing at the new data when used. They will find the
* record which has the same name in the new data.
*/

#pragma once

#include <stdint.h>
#include <stdio.h>
#include <cstring>
#include <algorithm>

class ShopData
{
public:
    ~ShopData();

    // Note: the memory will be modified, and it must stay around for the life of the object.
    bool LoadFromMemory(void* mem, uint32_t size);

    bool LoadFromFile(const char* fileName);

public:
    #pragma pack(push, 1)

    template <typename T>
    union Ptr64
    {
        T* ptr;
        uint64_t _64 = 0;
    };

    struct Bool
    {
        uint8_t _8 = 0;
        bool Get() const
        {
            return _8 != 0;
        }
    };

    #pragma pack(pop)

    template <typename T>
    struct Record
    {
    public:
        const T& Get() const
        {
            static const T s_dummy = T();
            return m_record ? *m_record : s_dummy;
        }

        bool Valid() const
        {
            return m_record != nullptr;
        }

    private:
        friend class ShopData;
        T* m_record = nullptr;
    };

public:
    #pragma pack(push, 1)
    struct Item
    {
        Ptr64<char> name;
        uint32_t sellCost;
        uint32_t buyCost;
    };

    using ItemRecord = Record<Item>;

    #pragma pack(pop)

private:
    template <typename T>
    inline static void EndianSwap(T& v)
    {
        uint8_t* bytes = reinterpret_cast<uint8_t*>(&v);
        for (size_t i = 0; i < sizeof(T) / 2; ++i)
        {
            uint8_t tmp = bytes[i];
            bytes[i] = bytes[sizeof(T) - 1 - i];
            bytes[sizeof(T) - 1 - i] = tmp;
        }
    }

    template <typename T>
    static bool Read(T& value, void* mem, uint32_t& memIndex, uint32_t memSize, bool endianSwap)
    {
        if (memSize - memIndex < sizeof(value))
            return false;

        memcpy(&value, &((char*)mem)[memIndex], sizeof(value));
        memIndex += sizeof(value);

        if (endianSwap)
            EndianSwap(value);

        return true;
    }

private:
    template <typename T>
    inline static void DoPointerFixup(T& v, void* base)
    {
    }

    template <typename T>
    inline static void DoPointerFixup(T*& v, void* base)
    {
        v = reinterpret_cast<T*>(reinterpret_cast<uintptr_t>(base) + reinterpret_cast<uintptr_t>(v));
    }

    template <typename T>
    inline static void DoPointerFixup(Ptr64<T>& v, void* base)
    {
        // null ptrs are preserved.
        if (v._64 == 0)
            return;
        v._64 += reinterpret_cast<uintptr_t>(base);
    }

private:
    template <typename T>
    inline static void DoEndianSwapAndPointerFixup(T& v, void* base, bool endianSwap)
    {
        if (endianSwap)
            EndianSwap(v);
        DoPointerFixup(v, base);
    }

    static void DoEndianSwapAndPointerFixup(Item& v, void* base, bool endianSwap);

private:
    uint8_t* m_ownedMemory = nullptr;

public:
    // Returns whether the data was updated or not (hot reloading).
    bool Tick()
    {
        return false;
    }

    template <typename T>
    inline uint32_t GetCount() const;

    template <typename T>
    inline Record<T> Get(uint32_t index) const;

    // An int version to catch index 0 not being ambiguous with nullptr
    template <typename T>
    inline Record<T> Get(int index) const
    {
        return Get((uint32_t)index);
    }

    template <typename T>
    inline Record<T> Get(const char* name) const;

    inline uint32_t GetItemCount() const;
    inline ItemRecord GetItem(uint32_t index) const;
    inline ItemRecord GetItem(int index) const
    {
        // An int version to catch index 0 not being ambiguous with nullptr
        return GetItem((uint32_t)index);
    }
    inline ItemRecord GetItem(const char* name) const;

private:
    uint32_t m_table_Item_count = 0;
    Ptr64<Ptr64<char>> m_table_Item_names;
    Ptr64<Item> m_table_Item;
};

// ================================= Misc =================================

inline ShopData::~ShopData()
{
    delete[] m_ownedMemory;
    m_ownedMemory = nullptr;
}

// ================================= LOADING =================================

inline bool ShopData::LoadFromMemory(void* mem, uint32_t memSize)
{
    auto MakeFourCC = [](char a, char b, char c, char d) -> uint32_t
    {
        return (uint32_t)(uint8_t)a
            | ((uint32_t)(uint8_t)b << 8)
            | ((uint32_t)(uint8_t)c << 16)
            | ((uint32_t)(uint8_t)d << 24);
    };

    uint32_t memIndex = 0;

    // verify fourcc, and see if we need to do endian swaps
    bool endianSwap = false;
    {
        static const uint32_t fourcc_regular = MakeFourCC('D', 'F', 'G', 'D');
        static const uint32_t fourcc_swapped = MakeFourCC('D', 'G', 'F', 'D');

        uint32_t fourcc = 0;
        if (!Read(fourcc, mem, memIndex, memSize, false))
            return false;

        if (fourcc == fourcc_swapped)
            endianSwap = true;
        else if (fourcc != fourcc_regular)
            return false;
    }

    // Verify that the schema hash in the binary data matches the schema hash this file was made for
    {
        uint64_t hash = 0;
        if (!Read(hash, mem, memIndex, memSize, endianSwap) || hash != 0xba2395692633945dULL)
            return false;
    }

    // Item Table
    {
        if (!Read(m_table_Item_count, mem, memIndex, memSize, endianSwap))
            return false;

        if (m_table_Item_count > 0)
        {
            // get char** to LUT and fixup string pointers
            if (memSize - memIndex < m_table_Item_count * sizeof(uint64_t))
                return false;
            m_table_Item_names._64 = memIndex;
            DoEndianSwapAndPointerFixup(m_table_Item_names, mem, endianSwap);
            for (uint32_t i = 0; i < m_table_Item_count; ++i)
                DoEndianSwapAndPointerFixup(m_table_Item_names.ptr[i], mem, endianSwap);
            memIndex += m_table_Item_count * sizeof(uint64_t);

            // Get a pointer to the first entry in the table
            if (memSize - memIndex < m_table_Item_count * sizeof(Item))
                return false;
            m_table_Item._64 = memIndex;
            DoEndianSwapAndPointerFixup(m_table_Item, mem, endianSwap);
            memIndex += m_table_Item_count * sizeof(Item);

            // Do pointer fixup
            for (uint32_t i = 0; i < m_table_Item_count; ++i)
                DoEndianSwapAndPointerFixup(m_table_Item.ptr[i], mem, endianSwap);
        }
    }

    return true;
}

inline bool ShopData::LoadFromFile(const char* fileName)
{
    FILE* file = nullptr;
    fopen_s(&file, fileName, "rb");
    if (!file)
        return false;

    fseek(file, 0, SEEK_END);
    uint32_t fileSize = (uint32_t)ftell(file);

    m_ownedMemory = new uint8_t[fileSize];
    fseek(file, 0, SEEK_SET);

    if (fread(m_ownedMemory, fileSize, 1, file) != 1)
        return false;

    fclose(file);

    bool ret = LoadFromMemory(m_ownedMemory, fileSize);

    return ret;
}

// ================================= Pointer Fixup =================================

inline void ShopData::DoEndianSwapAndPointerFixup(Item& v, void* base, bool endianSwap)
{
    DoEndianSwapAndPointerFixup(v.name, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.sellCost, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.buyCost, base, endianSwap);
}

// ================================= Public Interface =================================
template <>
inline uint32_t ShopData::GetCount<ShopData::Item>() const
{
    return m_table_Item_count;
}

template <>
inline ShopData::ItemRecord ShopData::Get<ShopData::Item>(uint32_t index) const
{
    ItemRecord ret;
    if (index < m_table_Item_count)
    {
        ret.m_record = &m_table_Item.ptr[index];
    }
    return ret;
}

template <>
inline ShopData::ItemRecord ShopData::Get<ShopData::Item>(const char* name) const
{
    ItemRecord ret;

    Ptr64<char>* array = m_table_Item_names.ptr;
    const uint32_t count = m_table_Item_count;

    auto it = std::lower_bound(
        array,
        array + count,
        name,
        [](const Ptr64<char>& item, const char* val)
        {
            return strcmp(item.ptr, val) < 0;
        }
    );

    uint32_t index = uint32_t(it - array);

    if (index < count && !strcmp(it->ptr, name))
    {
        ret.m_record = &m_table_Item.ptr[index];
    }

    return ret;
}

inline uint32_t ShopData::GetItemCount() const
{
    return GetCount<Item>();
}

inline ShopData::ItemRecord ShopData::GetItem(uint32_t index) const
{
    return Get<Item>(index);
}

inline ShopData::ItemRecord ShopData::GetItem(const char* name) const
{
    return Get<Item>(name);
}
