static constexpr const char* c_output_h = R"EMBED(/*
* This code was generated by df_game_data https://github.com/Atrix256/df_game_data
* Do not edit manually, unless you understand the consequences.
*/

#pragma once

#include <stdint.h>
#include <stdio.h>

class /*$ClassName$*/
{
public:
    ~/*$ClassName$*/()
    {
        delete[] m_ownedMemory;
        m_ownedMemory = nullptr;
    }

    // Note: the memory will be modified, and it must stay around for the life of the object.
    bool LoadFromMemory(void* mem, uint64_t size)
    {
        // TODO: do it!
        return false;
    }

    bool LoadFromFile(const char* fileName)
    {
        FILE* file = nullptr;
        fopen_s(&file, fileName, "rb");
        if (!file)
            return false;

        fseek(file, 0, SEEK_END);
        long fileSize = ftell(file);

        m_ownedMemory = new uint8_t[fileSize];
        fseek(file, 0, SEEK_SET);

        if (fread(m_ownedMemory, fileSize, 1, file) != 1)
            return false;

        fclose(file);

        bool ret = LoadFromMemory(m_ownedMemory, fileSize);

        return ret;
    }

private:
    uint8_t* m_ownedMemory = nullptr;
};
)EMBED";
