/*
* This code was generated by df_game_data https://github.com/Atrix256/df_game_data
* Do not edit manually, unless you understand the consequences.
*/

#pragma once

namespace /*$namespace$*/
{
    int i;
}
