static constexpr const char* c_output_h = R"EMBED(/*
* This code was generated by df_game_data https://github.com/Atrix256/df_game_data
* Do not edit manually, unless you understand the consequences.
*/

#pragma once

#include <stdint.h>

namespace /*$namespace$*/
{
    bool LoadFromMemory(void* mem, uint64_t size)
    {
        // TODO: do it!
        return false;
    }

    bool LoadFromFile(const char* fileName)
    {
        // TODO: load into memory and then call LoadFromMemory
        return false;
    }
};
)EMBED";
