static constexpr const char* c_file_text = R"EMBED(/*
This code was generated by df_game_data https://github.com/Atrix256/df_game_data
Do not edit manually, unless you understand the consequences.

    Do this:
        #define DF_GAMEDATA_IMPLEMENTATION
    before you include this file in *one* C or C++ file to create the implementation.

To use:

    InitDatabase()    - Initialize a database object. must be called before loading.
    DestroyDatabase() - Destroys a database object and frees any internal memory used.
    LoadFromMemory()  - Loads a database from a bin file in memory.
    LoadFromFile()    - Loads a database from a bin file on disk.
    Tick()            - Used for hot reloading. Returns true when hot reload happens, so you can update cached data.
    StringIndex()     - Returns the index of a record, given a name table and a name.

*/
// Made with df_game_data version /*$Version$*/

#pragma once

#include <stdint.h>
#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
/*$Includes$*/
#pragma pack(push, 1)
/*$EnumAndStructDefs$*/#pragma pack(pop)

typedef struct /*$ClassName$*/_Database
{
    uint8_t* ownedMemory;
/*$StructFields$*/} /*$ClassName$*/_Database;

// Public interface
void /*$ClassName$*/_InitDatabase(/*$ClassName$*/_Database* db);
void /*$ClassName$*/_DestroyDatabase(/*$ClassName$*/_Database* db);
bool /*$ClassName$*/_LoadFromMemory(void* mem, uint32_t size, /*$ClassName$*/_Database* db);
bool /*$ClassName$*/_LoadFromFile(const char* fileName, /*$ClassName$*/_Database* db);
bool /*$ClassName$*/_Tick(/*$ClassName$*/_Database* db);
size_t /*$ClassName$*/_StringIndex(const char** arr, size_t count, const char* key);

// Private implementation
#ifdef DF_GAMEDATA_IMPLEMENTATION

// From https://jcgt.org/published/0009/03/02/
// supplemental material uint pcg(uint v)
uint32_t /*$ClassName$*/_pcg_hash(uint32_t input)
{
    uint32_t state = input * 747796405u + 2891336453u;
    uint32_t word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}

int /*$ClassName$*/_CompareKeyToElement(const void* key, const void* elem)
{
    return strcmp((const char*)key, *(const char* const*)elem);
}

// Returns count if not found
size_t /*$ClassName$*/_StringIndex(const char** arr, size_t count, const char* key)
{
    char** hit = bsearch(key, arr, count, sizeof(const char*), /*$ClassName$*/_CompareKeyToElement);
    return hit ? (hit - arr) : count;
}

void /*$ClassName$*/_EndianSwap_U8(uint8_t* value)
{
    (void)value;
}

void /*$ClassName$*/_EndianSwap_U16(uint16_t* value)
{
    *value = ((*value & 0x00FF) << 8) |
             ((*value & 0xFF00) >> 8);
}

void /*$ClassName$*/_EndianSwap_U32(uint32_t* value)
{
    *value = ((*value & 0x000000FF) << 24) |
             ((*value & 0x0000FF00) << 8) |
             ((*value & 0x00FF0000) >> 8) |
             ((*value & 0xFF000000) >> 24);
}

void /*$ClassName$*/_EndianSwap_U64(uint64_t* value)
{
    *value = ((*value & 0x00000000000000FFULL) << 56) |
        ((*value & 0x000000000000FF00ULL) << 40) |
        ((*value & 0x0000000000FF0000ULL) << 24) |
        ((*value & 0x00000000FF000000ULL) << 8) |
        ((*value & 0x000000FF00000000ULL) >> 8) |
        ((*value & 0x0000FF0000000000ULL) >> 24) |
        ((*value & 0x00FF000000000000ULL) >> 40) |
        ((*value & 0xFF00000000000000ULL) >> 56);
}

bool /*$ClassName$*/_Read_U8(uint8_t* value, void* mem, uint32_t* memIndex, uint32_t memSize, bool endianSwap)
{
    if (memSize - *memIndex < sizeof(*value))
        return false;

    memcpy(value, &((uint8_t*)mem)[*memIndex], sizeof(*value));
    *memIndex += sizeof(*value);

    if (endianSwap)
        /*$ClassName$*/_EndianSwap_U8(value);

    return true;
}

bool /*$ClassName$*/_Read_U16(uint16_t* value, void* mem, uint32_t* memIndex, uint32_t memSize, bool endianSwap)
{
    if (memSize - *memIndex < sizeof(*value))
        return false;

    memcpy(value, &((uint8_t*)mem)[*memIndex], sizeof(*value));
    *memIndex += sizeof(*value);

    if (endianSwap)
        /*$ClassName$*/_EndianSwap_U16(value);

    return true;
}

bool /*$ClassName$*/_Read_U32(uint32_t* value, void* mem, uint32_t* memIndex, uint32_t memSize, bool endianSwap)
{
    if (memSize - *memIndex < sizeof(*value))
        return false;

    memcpy(value, &((uint8_t*)mem)[*memIndex], sizeof(*value));
    *memIndex += sizeof(*value);

    if (endianSwap)
        /*$ClassName$*/_EndianSwap_U32(value);

    return true;
}

bool /*$ClassName$*/_Read_U64(uint64_t* value, void* mem, uint32_t* memIndex, uint32_t memSize, bool endianSwap)
{
    if (memSize - *memIndex < sizeof(*value))
        return false;

    memcpy(value, &((uint8_t*)mem)[*memIndex], sizeof(*value));
    *memIndex += sizeof(*value);

    if (endianSwap)
        /*$ClassName$*/_EndianSwap_U64(value);

    return true;
}

void /*$ClassName$*/_DoEndianSwapAndPointerFixup_U8(uint8_t* value, void* mem, bool endianSwap)
{
    if (endianSwap)
        /*$ClassName$*/_EndianSwap_U8(value);
}

void /*$ClassName$*/_DoEndianSwapAndPointerFixup_U16(uint16_t* value, void* mem, bool endianSwap)
{
    if (endianSwap)
        /*$ClassName$*/_EndianSwap_U16(value);
}

void /*$ClassName$*/_DoEndianSwapAndPointerFixup_U32(uint32_t* value, void* mem, bool endianSwap)
{
    if (endianSwap)
        /*$ClassName$*/_EndianSwap_U32(value);
}

void /*$ClassName$*/_DoEndianSwapAndPointerFixup_U64(uint64_t* value, void* mem, bool endianSwap)
{
    if (endianSwap)
        /*$ClassName$*/_EndianSwap_U64(value);
}

void /*$ClassName$*/_DoEndianSwapAndPointerFixup_float(float* value, void* mem, bool endianSwap)
{
    if (endianSwap)
        /*$ClassName$*/_EndianSwap_U32((uint32_t*)value);
}

void /*$ClassName$*/_DoEndianSwapAndPointerFixup_double(double* value, void* mem, bool endianSwap)
{
    if (endianSwap)
        /*$ClassName$*/_EndianSwap_U64((uint64_t*)value);
}

void /*$ClassName$*/_DoEndianSwapAndPointerFixup_Ptr(uint64_t* value, void* mem, bool endianSwap)
{
    if (endianSwap)
        /*$ClassName$*/_EndianSwap_U64(value);
    if (*value != 0)
        *value += (uint64_t)mem;
}

/*$DoEndianSwapAndPointerFixups$*/void /*$ClassName$*/_InitDatabase(/*$ClassName$*/_Database* db)
{
    db->ownedMemory = NULL;
/*$StructInit$*/}

void /*$ClassName$*/_DestroyDatabase(/*$ClassName$*/_Database* db)
{
    if (db->ownedMemory)
    {
        free(db->ownedMemory);
        db->ownedMemory = NULL;
    }
/*$StructDeinit$*/}

bool /*$ClassName$*/_LoadFromMemory(void* mem, uint32_t memSize, /*$ClassName$*/_Database* db)
{
    #define MAKE_FOUR_CC(A, B, C, D) \
        ( (uint32_t)(uint8_t)A \
        | ((uint32_t)(uint8_t)B << 8) \
        | ((uint32_t)(uint8_t)C << 16) \
        | ((uint32_t)(uint8_t)D << 24))

    uint32_t memIndex = 0;

    // verify fourcc, and see if we need to do endian swaps
    bool endianSwap = false;
    {
        static const uint32_t fourcc_regular = MAKE_FOUR_CC('D', 'F', 'G', 'D');
        static const uint32_t fourcc_swapped = MAKE_FOUR_CC('D', 'G', 'F', 'D');

        uint32_t fourcc = 0;
        if (!/*$ClassName$*/_Read_U32(&fourcc, mem, &memIndex, memSize, false))
            return false;

        if (fourcc == fourcc_swapped)
            endianSwap = true;
        else if (fourcc != fourcc_regular)
            return false;
    }

    // Read the version number the binary file was made with.
    // Unused now, but can be used for backwards compatibility etc later.
    {
        uint8_t version[3];
        if (!/*$ClassName$*/_Read_U8(&version[0], mem, &memIndex, memSize, endianSwap) ||
            !/*$ClassName$*/_Read_U8(&version[1], mem, &memIndex, memSize, endianSwap) ||
            !/*$ClassName$*/_Read_U8(&version[2], mem, &memIndex, memSize, endianSwap))
        {
            return false;
        }
    }/*$Obfuscation$*/

    // Verify that the schema hash in the binary data matches the schema hash this file was made for
    {
        uint64_t hash = 0;
        if (!/*$ClassName$*/_Read_U64(&hash, mem, &memIndex, memSize, endianSwap) || hash != /*$SchemaHash$*/)
            return false;
    }
/*$LoadTables$*//*$LoadMemoryEnd$*/
    return true;
}

bool /*$ClassName$*/_LoadFromFile(const char* fileName, /*$ClassName$*/_Database* db)
{
    FILE* file = NULL;
    fopen_s(&file, fileName, "rb");
    if (!file)
        return false;

    fseek(file, 0, SEEK_END);
    uint32_t fileSize = (uint32_t)ftell(file);

    if (db->ownedMemory)
        free(db->ownedMemory);

    db->ownedMemory = malloc(fileSize);
    fseek(file, 0, SEEK_SET);

    if (fread(db->ownedMemory, fileSize, 1, file) != 1)
        return false;

    fclose(file);

    bool ret = /*$ClassName$*/_LoadFromMemory(db->ownedMemory, fileSize, db);
/*$LoadFileEnd$*/
    return ret;
}
/*$PrivateImplementation$*/#endif

/*
TODO:
* document how to use it at the top, like we do the C++ interface
* document hot reloading: tick returns true, then you need to update anything you cached.
*/
)EMBED";
