/*
* This code was generated by df_game_data https://github.com/Atrix256/df_game_data
* Do not edit manually, unless you understand the consequences.
*/

#pragma once

#include <stdint.h>
#include <stdio.h>
#include <cstring>
#include <algorithm>

class /*$ClassName$*/
{
public:
    ~/*$ClassName$*/();

    // Note: the memory will be modified, and it must stay around for the life of the object.
    bool LoadFromMemory(void* mem, uint32_t size);

    bool LoadFromFile(const char* fileName);

public:
    template <typename T>
    union Ptr64
    {
        T* ptr;
        uint64_t _64 = 0;
    };

    struct Bool
    {
        uint8_t _8 = 0;
        bool Get() const
        {
            return _8 != 0;
        }
    };

    template <typename T>
    struct Record
    {
    public:
        const T& Get() const
        {
            static const T s_dummy = T();
            return m_record ? *m_record : s_dummy;
        }

        bool Valid() const
        {
            return m_record != nullptr;
        }

    private:
        friend class /*$ClassName$*/;
        T* m_record = nullptr;
    };

public:
    #pragma pack(push, 1)
/*$EnumAndStructDefs$*/
    #pragma pack(pop)

private:
    template <typename T>
    inline static void EndianSwap(T& v)
    {
        uint8_t* bytes = reinterpret_cast<uint8_t*>(&v);
        for (size_t i = 0; i < sizeof(T) / 2; ++i)
        {
            uint8_t tmp = bytes[i];
            bytes[i] = bytes[sizeof(T) - 1 - i];
            bytes[sizeof(T) - 1 - i] = tmp;
        }
    }

    template <typename T>
    static bool Read(T& value, void* mem, uint32_t& memIndex, uint32_t memSize, bool endianSwap)
    {
        if (memSize - memIndex < sizeof(value))
            return false;

        memcpy(&value, &((char*)mem)[memIndex], sizeof(value));
        memIndex += sizeof(value);

        if (endianSwap)
            EndianSwap(value);

        return true;
    }

private:
    template <typename T>
    inline static void DoPointerFixup(T& v, void* base)
    {
    }

    template <typename T>
    inline static void DoPointerFixup(T*& v, void* base)
    {
        v = reinterpret_cast<T*>(reinterpret_cast<uintptr_t>(base) + reinterpret_cast<uintptr_t>(v));
    }

    template <typename T>
    inline static void DoPointerFixup(Ptr64<T>& v, void* base)
    {
        // null ptrs are preserved.
        if (v._64 == 0)
            return;
        v._64 += reinterpret_cast<uintptr_t>(base);
    }

private:
    template <typename T>
    inline static void DoEndianSwapAndPointerFixup(T& v, void* base, bool endianSwap)
    {
        if (endianSwap)
            EndianSwap(v);
        DoPointerFixup(v, base);
    }

/*$PointerFixupForwardDeclare$*/
private:
    uint8_t* m_ownedMemory = nullptr;

public:
/*$PublicInterface$*/
private:
/*$PrivateStorage$*/};

// ================================= Misc =================================

/*$ClassName$*/::~/*$ClassName$*/()
{
    delete[] m_ownedMemory;
    m_ownedMemory = nullptr;
}

// ================================= LOADING =================================

bool /*$ClassName$*/::LoadFromMemory(void* mem, uint32_t memSize)
{
    auto MakeFourCC = [](char a, char b, char c, char d) -> uint32_t
    {
        return (uint32_t)(uint8_t)a
            | ((uint32_t)(uint8_t)b << 8)
            | ((uint32_t)(uint8_t)c << 16)
            | ((uint32_t)(uint8_t)d << 24);
    };

    uint32_t memIndex = 0;

    // verify fourcc, and see if we need to do endian swaps
    bool endianSwap = false;
    {
        static const uint32_t fourcc_regular = MakeFourCC('D', 'F', 'G', 'D');
        static const uint32_t fourcc_swapped = MakeFourCC('D', 'G', 'F', 'D');

        uint32_t fourcc = 0;
        if (!Read(fourcc, mem, memIndex, memSize, false))
            return false;

        if (fourcc == fourcc_swapped)
            endianSwap = true;
        else if (fourcc != fourcc_regular)
            return false;
    }

    // Verify that the schema hash in the binary data matches the schema hash this file was made for
    {
        uint64_t hash = 0;
        if (!Read(hash, mem, memIndex, memSize, endianSwap) || hash != /*$SchemaHash*/)
            return false;
    }
/*$LoadTables$*/
    return true;
}

bool /*$ClassName$*/::LoadFromFile(const char* fileName)
{
    FILE* file = nullptr;
    fopen_s(&file, fileName, "rb");
    if (!file)
        return false;

    fseek(file, 0, SEEK_END);
    uint32_t fileSize = (uint32_t)ftell(file);

    m_ownedMemory = new uint8_t[fileSize];
    fseek(file, 0, SEEK_SET);

    if (fread(m_ownedMemory, fileSize, 1, file) != 1)
        return false;

    fclose(file);

    bool ret = LoadFromMemory(m_ownedMemory, fileSize);

    return ret;
}

// ================================= Pointer Fixup =================================
/*$PointerFixup$*/