namespace TestData;

enum Color : byte
{
    Brown = 2,
    Hazel = 7,
    Blue = 4,
    Green = 0
}

enum Flags : ubyte (bit_flags)
{
    Flag_1,
    Flag_2,
    Flag_3,
    Flag_4,
}

table Point2D { x:float; y:float; }
table Point3D { x:float; y:float; z:float; }
union Point {
  point_2D:Point2D,
  point_3D:Point3D,
  vector_2D:Point2D,
  vector_3D:Point3D,
}

// Root Type
table TableEntry
{
    //8 bits
    _bool: bool;
    _byte: byte;
    _ubyte: ubyte;

    // 16 bits
    _short:short;
    _ushort:ushort;

    // 32 bits
    _int:int;
    _uint:uint;

    // 64 bits
    _long:long;
    _ulong:ulong;

    // floating point
    _float:float;
    _double:double;

    _string:string = "test";
    _string_deprecated:string = "test" (deprecated);
    _color:Color;
    _union:Point;
    _flags:Flags;

    // todo: array of struct, array of union, array of array?
}

root_type TableEntry;
