/*
* This code was generated by df_game_data https://github.com/Atrix256/df_game_data
* Do not edit manually, unless you understand the consequences.
*
* To load data, call either of these functions:
*
* bool LoadFromMemory(void* mem, uint32_t size);
* bool LoadFromFile(const char* fileName);
*
* To get data entries after loading, there are functions like below, assuming "Item"
* is the table you want to get an entry from:
*
* uint32 GetItemCount();                - Get the number of items
* ItemRecord GetItem(uint32_t index);   - Get item by index
* ItemRecord GetItem(const char* name); - Get item by name, if entry name look up table enabled in settings
*
* There are also templated functions of this form:
*
* uint32 GetCount<T>()
* Record<T> Get<T>(uint32_t index)
* Record<T> Get<T>(const char* name)
*
* For hot reloading, call Tick() periodically to check if the bin file on disk has changed.
* If it has changed, Tick() will return true after reloading the data file.
*
* Record objects will start pointing at the new data when used. They will find the
* record which has the same name in the new data.
*/
// Made with df_game_data version 1.0.0

#pragma once

#include <stdint.h>
#include <stdio.h>
#include <cstring>

class Data
{
public:
    ~Data();

    // Note: the memory will be modified, and it must stay around for the life of the object.
    bool LoadFromMemory(void* mem, uint32_t size);

    bool LoadFromFile(const char* fileName);

public:
    #pragma pack(push, 1)

    template <typename T>
    union Ptr64
    {
        T* ptr;
        uint64_t _64 = 0;
    };

    struct Bool
    {
        uint8_t _8 = 0;
        bool Get() const
        {
            return _8 != 0;
        }
    };

    #pragma pack(pop)

    template <typename T>
    struct Record
    {
    public:
        const T& Get() const
        {
            static const T s_dummy = T();
            return m_record ? *m_record : s_dummy;
        }

        bool Valid() const
        {
            return m_record != nullptr;
        }

    private:
        friend class Data;
        T* m_record = nullptr;
    };

public:
    #pragma pack(push, 1)

    enum class Color : uint16_t
    {
        Brown,
        Hazel,
        Blue,
        Green,
    };

    struct Pos
    {
        float x;
        float y;
    };

    struct People
    {
        Ptr64<char> name;
    };

    using PeopleRecord = Record<People>;

    enum class UTest_type : uint16_t
    {
        None,
        _pos,
        _float,
    };

    struct UTest
    {
        UTest_type type;
        Ptr64<void> ptr;

        using _pos_type = Pos;
        using _float_type = float;

        _pos_type* _pos() { return type == UTest_type::_pos ? reinterpret_cast<_pos_type*>(ptr.ptr) : nullptr; }
        const _pos_type* _pos() const { return type == UTest_type::_pos ? reinterpret_cast<const _pos_type*>(ptr.ptr) : nullptr; }

        _float_type* _float() { return type == UTest_type::_float ? reinterpret_cast<_float_type*>(ptr.ptr) : nullptr; }
        const _float_type* _float() const { return type == UTest_type::_float ? reinterpret_cast<const _float_type*>(ptr.ptr) : nullptr; }
    };

    struct EntryAll
    {
        Bool _bool;
        uint8_t _uint8;
        int8_t _sint8;
        uint16_t _uint16;
        int16_t _sint16;
        uint32_t _uint32;
        int32_t _sint32;
        uint64_t _uint64;
        int64_t _sint64;
        float _float;
        double _double;
        Ptr64<char> _string;
        Color _color;
        Pos _pos;
        Ptr64<People> _people;
        UTest _UTest;
    };

    struct EntryDefault
    {
        Bool _bool;
        uint8_t _uint8;
        int8_t _sint8;
        uint16_t _uint16;
        int16_t _sint16;
        uint32_t _uint32;
        int32_t _sint32;
        uint64_t _uint64;
        int64_t _sint64;
        float _float;
        double _double;
        Ptr64<char> _string;
        Color _color;
        Ptr64<People> _people;
    };

    struct EntryArrayDynamic
    {
        uint32_t _bool_count = 0;
        Ptr64<Bool> _bool;
        uint32_t _uint8_count = 0;
        Ptr64<uint8_t> _uint8;
        uint32_t _sint8_count = 0;
        Ptr64<int8_t> _sint8;
        uint32_t _uint16_count = 0;
        Ptr64<uint16_t> _uint16;
        uint32_t _sint16_count = 0;
        Ptr64<int16_t> _sint16;
        uint32_t _uint32_count = 0;
        Ptr64<uint32_t> _uint32;
        uint32_t _sint32_count = 0;
        Ptr64<int32_t> _sint32;
        uint32_t _uint64_count = 0;
        Ptr64<uint64_t> _uint64;
        uint32_t _sint64_count = 0;
        Ptr64<int64_t> _sint64;
        uint32_t _float_count = 0;
        Ptr64<float> _float;
        uint32_t _double_count = 0;
        Ptr64<double> _double;
        uint32_t _string_count = 0;
        Ptr64<Ptr64<char>> _string;
        uint32_t _color_count = 0;
        Ptr64<Color> _color;
        uint32_t _pos_count = 0;
        Ptr64<Pos> _pos;
        uint32_t _people_count = 0;
        Ptr64<Ptr64<People>> _people;
        uint32_t _UTest_count = 0;
        Ptr64<UTest> _UTest;
    };

    struct EntryArray2
    {
        static const uint32_t _bool_count = 2;
        Bool _bool[2];
        static const uint32_t _uint8_count = 2;
        uint8_t _uint8[2];
        static const uint32_t _sint8_count = 2;
        int8_t _sint8[2];
        static const uint32_t _uint16_count = 2;
        uint16_t _uint16[2];
        static const uint32_t _sint16_count = 2;
        int16_t _sint16[2];
        static const uint32_t _uint32_count = 2;
        uint32_t _uint32[2];
        static const uint32_t _sint32_count = 2;
        int32_t _sint32[2];
        static const uint32_t _uint64_count = 2;
        uint64_t _uint64[2];
        static const uint32_t _sint64_count = 2;
        int64_t _sint64[2];
        static const uint32_t _float_count = 2;
        float _float[2];
        static const uint32_t _double_count = 2;
        double _double[2];
        static const uint32_t _string_count = 2;
        Ptr64<char> _string[2];
        static const uint32_t _color_count = 2;
        Color _color[2];
        static const uint32_t _pos_count = 2;
        Pos _pos[2];
        static const uint32_t _people_count = 2;
        Ptr64<People> _people[2];
        static const uint32_t _UTest_count = 2;
        UTest _UTest[2];
    };

    struct Entry
    {
        EntryAll entries;
        EntryDefault entries_defaults;
        EntryArrayDynamic entries_dynamic_arrays;
        EntryArray2 entries_static_arrays;
    };

    using EntryRecord = Record<Entry>;

    #pragma pack(pop)

private:
    template <typename T>
    inline static void EndianSwap(T& v)
    {
        uint8_t* bytes = reinterpret_cast<uint8_t*>(&v);
        for (size_t i = 0; i < sizeof(T) / 2; ++i)
        {
            uint8_t tmp = bytes[i];
            bytes[i] = bytes[sizeof(T) - 1 - i];
            bytes[sizeof(T) - 1 - i] = tmp;
        }
    }

    template <typename T>
    static bool Read(T& value, void* mem, uint32_t& memIndex, uint32_t memSize, bool endianSwap)
    {
        if (memSize - memIndex < sizeof(value))
            return false;

        memcpy(&value, &((char*)mem)[memIndex], sizeof(value));
        memIndex += sizeof(value);

        if (endianSwap)
            EndianSwap(value);

        return true;
    }

private:
    template <typename T>
    inline static void DoPointerFixup(T& v, void* base)
    {
    }

    template <typename T>
    inline static void DoPointerFixup(T*& v, void* base)
    {
        v = reinterpret_cast<T*>(reinterpret_cast<uintptr_t>(base) + reinterpret_cast<uintptr_t>(v));
    }

    template <typename T>
    inline static void DoPointerFixup(Ptr64<T>& v, void* base)
    {
        // null ptrs are preserved.
        if (v._64 == 0)
            return;
        v._64 += reinterpret_cast<uintptr_t>(base);
    }

private:
    template <typename T>
    inline static void DoEndianSwapAndPointerFixup(T& v, void* base, bool endianSwap)
    {
        if (endianSwap)
            EndianSwap(v);
        DoPointerFixup(v, base);
    }

    static void DoEndianSwapAndPointerFixup(Pos& v, void* base, bool endianSwap);
    static void DoEndianSwapAndPointerFixup(People& v, void* base, bool endianSwap);
    static void DoEndianSwapAndPointerFixup(UTest& v, void* base, bool endianSwap);
    static void DoEndianSwapAndPointerFixup(EntryAll& v, void* base, bool endianSwap);
    static void DoEndianSwapAndPointerFixup(EntryDefault& v, void* base, bool endianSwap);
    static void DoEndianSwapAndPointerFixup(EntryArrayDynamic& v, void* base, bool endianSwap);
    static void DoEndianSwapAndPointerFixup(EntryArray2& v, void* base, bool endianSwap);
    static void DoEndianSwapAndPointerFixup(Entry& v, void* base, bool endianSwap);

private:
    uint8_t* m_ownedMemory = nullptr;

public:
    // Returns whether the data was updated or not (hot reloading).
    bool Tick()
    {
        return false;
    }

    template <typename T>
    inline uint32_t GetCount() const;

    template <typename T>
    inline Record<T> Get(uint32_t index) const;

    // An int version to catch index 0 not being ambiguous with nullptr
    template <typename T>
    inline Record<T> Get(int index) const
    {
        return Get((uint32_t)index);
    }

    inline uint32_t GetPeopleCount() const;
    inline PeopleRecord GetPeople(uint32_t index) const;
    inline PeopleRecord GetPeople(int index) const
    {
        // An int version to catch index 0 not being ambiguous with nullptr
        return GetPeople((uint32_t)index);
    }

    inline uint32_t GetEntryCount() const;
    inline EntryRecord GetEntry(uint32_t index) const;
    inline EntryRecord GetEntry(int index) const
    {
        // An int version to catch index 0 not being ambiguous with nullptr
        return GetEntry((uint32_t)index);
    }

private:
    uint32_t m_table_Entry_count = 0;
    Ptr64<Entry> m_table_Entry;

    uint32_t m_table_People_count = 0;
    Ptr64<People> m_table_People;
};

// ================================= Misc =================================

inline Data::~Data()
{
    delete[] m_ownedMemory;
    m_ownedMemory = nullptr;
}

// ================================= LOADING =================================

inline bool Data::LoadFromMemory(void* mem, uint32_t memSize)
{
    auto MakeFourCC = [](char a, char b, char c, char d) -> uint32_t
    {
        return (uint32_t)(uint8_t)a
            | ((uint32_t)(uint8_t)b << 8)
            | ((uint32_t)(uint8_t)c << 16)
            | ((uint32_t)(uint8_t)d << 24);
    };

    uint32_t memIndex = 0;

    // verify fourcc, and see if we need to do endian swaps
    bool endianSwap = false;
    {
        static const uint32_t fourcc_regular = MakeFourCC('D', 'F', 'G', 'D');
        static const uint32_t fourcc_swapped = MakeFourCC('D', 'G', 'F', 'D');

        uint32_t fourcc = 0;
        if (!Read(fourcc, mem, memIndex, memSize, false))
            return false;

        if (fourcc == fourcc_swapped)
            endianSwap = true;
        else if (fourcc != fourcc_regular)
            return false;
    }

    // Read the version number the binary file was made with.
    // Unused now, but can be used for backwards compatibility etc later.
    {
        uint8_t version[3];
        if (!Read(version[0], mem, memIndex, memSize, endianSwap) ||
            !Read(version[1], mem, memIndex, memSize, endianSwap) ||
            !Read(version[2], mem, memIndex, memSize, endianSwap))
        {
            return false;
        }
    }

    // Verify that the schema hash in the binary data matches the schema hash this file was made for
    {
        uint64_t hash = 0;
        if (!Read(hash, mem, memIndex, memSize, endianSwap) || hash != 0x50a230271e6f0e13ULL)
            return false;
    }

    // Entry Table
    {
        if (!Read(m_table_Entry_count, mem, memIndex, memSize, endianSwap))
            return false;

        if (m_table_Entry_count > 0)
        {
            // Get a pointer to the first entry in the table
            if (memSize - memIndex < m_table_Entry_count * sizeof(Entry))
                return false;
            m_table_Entry._64 = memIndex;
            DoEndianSwapAndPointerFixup(m_table_Entry, mem, endianSwap);
            memIndex += m_table_Entry_count * sizeof(Entry);

            // Do pointer fixup
            for (uint32_t i = 0; i < m_table_Entry_count; ++i)
                DoEndianSwapAndPointerFixup(m_table_Entry.ptr[i], mem, endianSwap);
        }
    }

    // People Table
    {
        if (!Read(m_table_People_count, mem, memIndex, memSize, endianSwap))
            return false;

        if (m_table_People_count > 0)
        {
            // Get a pointer to the first entry in the table
            if (memSize - memIndex < m_table_People_count * sizeof(People))
                return false;
            m_table_People._64 = memIndex;
            DoEndianSwapAndPointerFixup(m_table_People, mem, endianSwap);
            memIndex += m_table_People_count * sizeof(People);

            // Do pointer fixup
            for (uint32_t i = 0; i < m_table_People_count; ++i)
                DoEndianSwapAndPointerFixup(m_table_People.ptr[i], mem, endianSwap);
        }
    }

    return true;
}

inline bool Data::LoadFromFile(const char* fileName)
{
    FILE* file = nullptr;
    fopen_s(&file, fileName, "rb");
    if (!file)
        return false;

    fseek(file, 0, SEEK_END);
    uint32_t fileSize = (uint32_t)ftell(file);

    m_ownedMemory = new uint8_t[fileSize];
    fseek(file, 0, SEEK_SET);

    if (fread(m_ownedMemory, fileSize, 1, file) != 1)
        return false;

    fclose(file);

    bool ret = LoadFromMemory(m_ownedMemory, fileSize);

    return ret;
}

// ================================= Pointer Fixup =================================

inline void Data::DoEndianSwapAndPointerFixup(Pos& v, void* base, bool endianSwap)
{
    DoEndianSwapAndPointerFixup(v.x, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.y, base, endianSwap);
}

inline void Data::DoEndianSwapAndPointerFixup(People& v, void* base, bool endianSwap)
{
    DoEndianSwapAndPointerFixup(v.name, base, endianSwap);
}

inline void Data::DoEndianSwapAndPointerFixup(UTest& v, void* base, bool endianSwap)
{
    DoEndianSwapAndPointerFixup(v.type, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.ptr, base, endianSwap);
    switch(v.type)
    {
        case UTest_type::_pos:DoEndianSwapAndPointerFixup(*v._pos(), base, endianSwap); break;
        case UTest_type::_float:DoEndianSwapAndPointerFixup(*v._float(), base, endianSwap); break;
    }
}

inline void Data::DoEndianSwapAndPointerFixup(EntryAll& v, void* base, bool endianSwap)
{
    DoEndianSwapAndPointerFixup(v._bool, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint8, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._sint8, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint16, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._sint16, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint32, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._sint32, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint64, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._sint64, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._float, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._double, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._string, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._color, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._pos, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._people, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._UTest, base, endianSwap);
}

inline void Data::DoEndianSwapAndPointerFixup(EntryDefault& v, void* base, bool endianSwap)
{
    DoEndianSwapAndPointerFixup(v._bool, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint8, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._sint8, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint16, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._sint16, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint32, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._sint32, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint64, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._sint64, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._float, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._double, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._string, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._color, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._people, base, endianSwap);
}

inline void Data::DoEndianSwapAndPointerFixup(EntryArrayDynamic& v, void* base, bool endianSwap)
{
    DoEndianSwapAndPointerFixup(v._bool_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._bool, base, endianSwap);
    for (uint32_t i = 0; i < v._bool_count; ++i)
        DoEndianSwapAndPointerFixup(v._bool.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint8_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint8, base, endianSwap);
    for (uint32_t i = 0; i < v._uint8_count; ++i)
        DoEndianSwapAndPointerFixup(v._uint8.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._sint8_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._sint8, base, endianSwap);
    for (uint32_t i = 0; i < v._sint8_count; ++i)
        DoEndianSwapAndPointerFixup(v._sint8.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint16_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint16, base, endianSwap);
    for (uint32_t i = 0; i < v._uint16_count; ++i)
        DoEndianSwapAndPointerFixup(v._uint16.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._sint16_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._sint16, base, endianSwap);
    for (uint32_t i = 0; i < v._sint16_count; ++i)
        DoEndianSwapAndPointerFixup(v._sint16.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint32_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint32, base, endianSwap);
    for (uint32_t i = 0; i < v._uint32_count; ++i)
        DoEndianSwapAndPointerFixup(v._uint32.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._sint32_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._sint32, base, endianSwap);
    for (uint32_t i = 0; i < v._sint32_count; ++i)
        DoEndianSwapAndPointerFixup(v._sint32.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint64_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint64, base, endianSwap);
    for (uint32_t i = 0; i < v._uint64_count; ++i)
        DoEndianSwapAndPointerFixup(v._uint64.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._sint64_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._sint64, base, endianSwap);
    for (uint32_t i = 0; i < v._sint64_count; ++i)
        DoEndianSwapAndPointerFixup(v._sint64.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._float_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._float, base, endianSwap);
    for (uint32_t i = 0; i < v._float_count; ++i)
        DoEndianSwapAndPointerFixup(v._float.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._double_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._double, base, endianSwap);
    for (uint32_t i = 0; i < v._double_count; ++i)
        DoEndianSwapAndPointerFixup(v._double.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._string_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._string, base, endianSwap);
    for (uint32_t i = 0; i < v._string_count; ++i)
        DoEndianSwapAndPointerFixup(v._string.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._color_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._color, base, endianSwap);
    for (uint32_t i = 0; i < v._color_count; ++i)
        DoEndianSwapAndPointerFixup(v._color.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._pos_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._pos, base, endianSwap);
    for (uint32_t i = 0; i < v._pos_count; ++i)
        DoEndianSwapAndPointerFixup(v._pos.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._people_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._people, base, endianSwap);
    for (uint32_t i = 0; i < v._people_count; ++i)
        DoEndianSwapAndPointerFixup(v._people.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._UTest_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._UTest, base, endianSwap);
    for (uint32_t i = 0; i < v._UTest_count; ++i)
        DoEndianSwapAndPointerFixup(v._UTest.ptr[i], base, endianSwap);
}

inline void Data::DoEndianSwapAndPointerFixup(EntryArray2& v, void* base, bool endianSwap)
{
    for (uint32_t i = 0; i < v._bool_count; ++i)
        DoEndianSwapAndPointerFixup(v._bool[i], base, endianSwap);
    for (uint32_t i = 0; i < v._uint8_count; ++i)
        DoEndianSwapAndPointerFixup(v._uint8[i], base, endianSwap);
    for (uint32_t i = 0; i < v._sint8_count; ++i)
        DoEndianSwapAndPointerFixup(v._sint8[i], base, endianSwap);
    for (uint32_t i = 0; i < v._uint16_count; ++i)
        DoEndianSwapAndPointerFixup(v._uint16[i], base, endianSwap);
    for (uint32_t i = 0; i < v._sint16_count; ++i)
        DoEndianSwapAndPointerFixup(v._sint16[i], base, endianSwap);
    for (uint32_t i = 0; i < v._uint32_count; ++i)
        DoEndianSwapAndPointerFixup(v._uint32[i], base, endianSwap);
    for (uint32_t i = 0; i < v._sint32_count; ++i)
        DoEndianSwapAndPointerFixup(v._sint32[i], base, endianSwap);
    for (uint32_t i = 0; i < v._uint64_count; ++i)
        DoEndianSwapAndPointerFixup(v._uint64[i], base, endianSwap);
    for (uint32_t i = 0; i < v._sint64_count; ++i)
        DoEndianSwapAndPointerFixup(v._sint64[i], base, endianSwap);
    for (uint32_t i = 0; i < v._float_count; ++i)
        DoEndianSwapAndPointerFixup(v._float[i], base, endianSwap);
    for (uint32_t i = 0; i < v._double_count; ++i)
        DoEndianSwapAndPointerFixup(v._double[i], base, endianSwap);
    for (uint32_t i = 0; i < v._string_count; ++i)
        DoEndianSwapAndPointerFixup(v._string[i], base, endianSwap);
    for (uint32_t i = 0; i < v._color_count; ++i)
        DoEndianSwapAndPointerFixup(v._color[i], base, endianSwap);
    for (uint32_t i = 0; i < v._pos_count; ++i)
        DoEndianSwapAndPointerFixup(v._pos[i], base, endianSwap);
    for (uint32_t i = 0; i < v._people_count; ++i)
        DoEndianSwapAndPointerFixup(v._people[i], base, endianSwap);
    for (uint32_t i = 0; i < v._UTest_count; ++i)
        DoEndianSwapAndPointerFixup(v._UTest[i], base, endianSwap);
}

inline void Data::DoEndianSwapAndPointerFixup(Entry& v, void* base, bool endianSwap)
{
    DoEndianSwapAndPointerFixup(v.entries, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.entries_defaults, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.entries_dynamic_arrays, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.entries_static_arrays, base, endianSwap);
}

// ================================= Public Interface =================================
template <>
inline uint32_t Data::GetCount<Data::Entry>() const
{
    return m_table_Entry_count;
}

template <>
inline Data::EntryRecord Data::Get<Data::Entry>(uint32_t index) const
{
    EntryRecord ret;
    if (index < m_table_Entry_count)
    {
        ret.m_record = &m_table_Entry.ptr[index];
    }
    return ret;
}

inline uint32_t Data::GetEntryCount() const
{
    return GetCount<Entry>();
}

inline Data::EntryRecord Data::GetEntry(uint32_t index) const
{
    return Get<Entry>(index);
}

template <>
inline uint32_t Data::GetCount<Data::People>() const
{
    return m_table_People_count;
}

template <>
inline Data::PeopleRecord Data::Get<Data::People>(uint32_t index) const
{
    PeopleRecord ret;
    if (index < m_table_People_count)
    {
        ret.m_record = &m_table_People.ptr[index];
    }
    return ret;
}

inline uint32_t Data::GetPeopleCount() const
{
    return GetCount<People>();
}

inline Data::PeopleRecord Data::GetPeople(uint32_t index) const
{
    return Get<People>(index);
}
