/*
* This code was generated by df_game_data https://github.com/Atrix256/df_game_data
* Do not edit manually, unless you understand the consequences.
*
* To load data, call either of these functions:
*
* bool LoadFromMemory(void* mem, uint32_t size);
* bool LoadFromFile(const char* fileName);
*
* To get data entries after loading, there are functions like below, assuming "Item"
* is the table you want to get an entry from:
*
* uint32 GetItemCount();                - Get the number of items
* ItemRecord GetItem(uint32_t index);   - Get item by index
* ItemRecord GetItem(const char* name); - Get item by name, if entry name look up table enabled in settings
*
* There are also templated functions of this form:
*
* uint32 GetCount<T>()
* Record<T> Get<T>(uint32_t index)
* Record<T> Get<T>(const char* name)
*
* For hot reloading, call Tick() periodically to check if the bin file on disk has changed.
* If it has changed, Tick() will return true after reloading the data file.
*
* Record objects will start pointing at the new data when used. They will find the
* record which has the same name in the new data.
*/

#pragma once

#include <stdint.h>
#include <stdio.h>
#include <cstring>
#include <algorithm>

class Data
{
public:
    ~Data();

    // Note: the memory will be modified, and it must stay around for the life of the object.
    bool LoadFromMemory(void* mem, uint32_t size);

    bool LoadFromFile(const char* fileName);

public:
    #pragma pack(push, 1)

    template <typename T>
    union Ptr64
    {
        T* ptr;
        uint64_t _64 = 0;
    };

    struct Bool
    {
        uint8_t _8 = 0;
        bool Get() const
        {
            return _8 != 0;
        }
    };

    #pragma pack(pop)

    template <typename T>
    struct Record
    {
    public:
        const T& Get() const
        {
            static const T s_dummy = T();
            return m_record ? *m_record : s_dummy;
        }

        bool Valid() const
        {
            return m_record != nullptr;
        }

    private:
        friend class Data;
        T* m_record = nullptr;
    };

public:
    #pragma pack(push, 1)

    enum class Color : uint16_t
    {
        Brown,
        Hazel,
        Blue,
        Green,
    };

    struct Pos
    {
        float x;
        float y;
    };

    struct EntryAll
    {
        Bool _bool;
        uint8_t _uint8;
        int8_t _int8;
        uint16_t _uint16;
        int16_t _int16;
        uint32_t _uint32;
        int32_t _int32;
        uint64_t _uint64;
        int64_t _int64;
        float _float;
        double _double;
        Color _color;
        Pos _pos;
    };

    struct EntryDefault
    {
        Bool _bool;
        uint8_t _uint8;
        int8_t _int8;
        uint16_t _uint16;
        int16_t _int16;
        uint32_t _uint32;
        int32_t _int32;
        uint64_t _uint64;
        int64_t _int64;
        float _float;
        double _double;
        Color _color;
    };

    struct EntryArrayDynamic
    {
        uint32_t _bool_count = 0;
        Ptr64<Bool> _bool;
        uint32_t _uint8_count = 0;
        Ptr64<uint8_t> _uint8;
        uint32_t _int8_count = 0;
        Ptr64<int8_t> _int8;
        uint32_t _uint16_count = 0;
        Ptr64<uint16_t> _uint16;
        uint32_t _int16_count = 0;
        Ptr64<int16_t> _int16;
        uint32_t _uint32_count = 0;
        Ptr64<uint32_t> _uint32;
        uint32_t _int32_count = 0;
        Ptr64<int32_t> _int32;
        uint32_t _uint64_count = 0;
        Ptr64<uint64_t> _uint64;
        uint32_t _int64_count = 0;
        Ptr64<int64_t> _int64;
        uint32_t _float_count = 0;
        Ptr64<float> _float;
        uint32_t _double_count = 0;
        Ptr64<double> _double;
        uint32_t _color_count = 0;
        Ptr64<Color> _color;
        uint32_t _pos_count = 0;
        Ptr64<Pos> _pos;
    };

    struct EntryArray4
    {
        static const uint32_t _bool_count = 4;
        Bool _bool[4];
        static const uint32_t _uint8_count = 4;
        uint8_t _uint8[4];
        static const uint32_t _int8_count = 4;
        int8_t _int8[4];
        static const uint32_t _uint16_count = 4;
        uint16_t _uint16[4];
        static const uint32_t _int16_count = 4;
        int16_t _int16[4];
        static const uint32_t _uint32_count = 4;
        uint32_t _uint32[4];
        static const uint32_t _int32_count = 4;
        int32_t _int32[4];
        static const uint32_t _uint64_count = 4;
        uint64_t _uint64[4];
        static const uint32_t _int64_count = 4;
        int64_t _int64[4];
        static const uint32_t _float_count = 4;
        float _float[4];
        static const uint32_t _double_count = 4;
        double _double[4];
        static const uint32_t _color_count = 4;
        Color _color[4];
        static const uint32_t _pos_count = 4;
        Pos _pos[4];
    };

    struct Entry
    {
        EntryAll entries;
        EntryDefault entries_defaults;
        EntryArrayDynamic entries_dynamic_arrays;
        EntryArray4 entries_static_arrays;
    };

    using EntryRecord = Record<Entry>;

    #pragma pack(pop)

private:
    template <typename T>
    inline static void EndianSwap(T& v)
    {
        uint8_t* bytes = reinterpret_cast<uint8_t*>(&v);
        for (size_t i = 0; i < sizeof(T) / 2; ++i)
        {
            uint8_t tmp = bytes[i];
            bytes[i] = bytes[sizeof(T) - 1 - i];
            bytes[sizeof(T) - 1 - i] = tmp;
        }
    }

    template <typename T>
    static bool Read(T& value, void* mem, uint32_t& memIndex, uint32_t memSize, bool endianSwap)
    {
        if (memSize - memIndex < sizeof(value))
            return false;

        memcpy(&value, &((char*)mem)[memIndex], sizeof(value));
        memIndex += sizeof(value);

        if (endianSwap)
            EndianSwap(value);

        return true;
    }

private:
    template <typename T>
    inline static void DoPointerFixup(T& v, void* base)
    {
    }

    template <typename T>
    inline static void DoPointerFixup(T*& v, void* base)
    {
        v = reinterpret_cast<T*>(reinterpret_cast<uintptr_t>(base) + reinterpret_cast<uintptr_t>(v));
    }

    template <typename T>
    inline static void DoPointerFixup(Ptr64<T>& v, void* base)
    {
        // null ptrs are preserved.
        if (v._64 == 0)
            return;
        v._64 += reinterpret_cast<uintptr_t>(base);
    }

private:
    template <typename T>
    inline static void DoEndianSwapAndPointerFixup(T& v, void* base, bool endianSwap)
    {
        if (endianSwap)
            EndianSwap(v);
        DoPointerFixup(v, base);
    }

    static void DoEndianSwapAndPointerFixup(Pos& v, void* base, bool endianSwap);
    static void DoEndianSwapAndPointerFixup(EntryAll& v, void* base, bool endianSwap);
    static void DoEndianSwapAndPointerFixup(EntryDefault& v, void* base, bool endianSwap);
    static void DoEndianSwapAndPointerFixup(EntryArrayDynamic& v, void* base, bool endianSwap);
    static void DoEndianSwapAndPointerFixup(EntryArray4& v, void* base, bool endianSwap);
    static void DoEndianSwapAndPointerFixup(Entry& v, void* base, bool endianSwap);

private:
    uint8_t* m_ownedMemory = nullptr;

public:
    // Returns whether the data was updated or not (hot reloading).
    bool Tick()
    {
        return false;
    }

    template <typename T>
    inline uint32_t GetCount() const;

    template <typename T>
    inline Record<T> Get(uint32_t index) const;

    // An int version to catch index 0 not being ambiguous with nullptr
    template <typename T>
    inline Record<T> Get(int index) const
    {
        return Get((uint32_t)index);
    }

    template <typename T>
    inline Record<T> Get(const char* name) const;

    inline uint32_t GetEntryCount() const;
    inline EntryRecord GetEntry(uint32_t index) const;
    inline EntryRecord GetEntry(int index) const
    {
        // An int version to catch index 0 not being ambiguous with nullptr
        return GetEntry((uint32_t)index);
    }
    inline EntryRecord GetEntry(const char* name) const;

private:
    uint32_t m_table_Entry_count = 0;
    Ptr64<Ptr64<char>> m_table_Entry_names;
    Ptr64<Entry> m_table_Entry;
};

// ================================= Misc =================================

inline Data::~Data()
{
    delete[] m_ownedMemory;
    m_ownedMemory = nullptr;
}

// ================================= LOADING =================================

inline bool Data::LoadFromMemory(void* mem, uint32_t memSize)
{
    auto MakeFourCC = [](char a, char b, char c, char d) -> uint32_t
    {
        return (uint32_t)(uint8_t)a
            | ((uint32_t)(uint8_t)b << 8)
            | ((uint32_t)(uint8_t)c << 16)
            | ((uint32_t)(uint8_t)d << 24);
    };

    uint32_t memIndex = 0;

    // verify fourcc, and see if we need to do endian swaps
    bool endianSwap = false;
    {
        static const uint32_t fourcc_regular = MakeFourCC('D', 'F', 'G', 'D');
        static const uint32_t fourcc_swapped = MakeFourCC('D', 'G', 'F', 'D');

        uint32_t fourcc = 0;
        if (!Read(fourcc, mem, memIndex, memSize, false))
            return false;

        if (fourcc == fourcc_swapped)
            endianSwap = true;
        else if (fourcc != fourcc_regular)
            return false;
    }

    // Verify that the schema hash in the binary data matches the schema hash this file was made for
    {
        uint64_t hash = 0;
        if (!Read(hash, mem, memIndex, memSize, endianSwap) || hash != 0x07409f9ee6f974f7ULL)
            return false;
    }

    // Entry Table
    {
        if (!Read(m_table_Entry_count, mem, memIndex, memSize, endianSwap))
            return false;

        if (m_table_Entry_count > 0)
        {
            // get char** to LUT and fixup string pointers
            if (memSize - memIndex < m_table_Entry_count * sizeof(uint64_t))
                return false;
            m_table_Entry_names._64 = memIndex;
            DoEndianSwapAndPointerFixup(m_table_Entry_names, mem, endianSwap);
            for (uint32_t i = 0; i < m_table_Entry_count; ++i)
                DoEndianSwapAndPointerFixup(m_table_Entry_names.ptr[i], mem, endianSwap);
            memIndex += m_table_Entry_count * sizeof(uint64_t);

            // Get a pointer to the first entry in the table
            if (memSize - memIndex < m_table_Entry_count * sizeof(Entry))
                return false;
            m_table_Entry._64 = memIndex;
            DoEndianSwapAndPointerFixup(m_table_Entry, mem, endianSwap);
            memIndex += m_table_Entry_count * sizeof(Entry);

            // Do pointer fixup
            for (uint32_t i = 0; i < m_table_Entry_count; ++i)
                DoEndianSwapAndPointerFixup(m_table_Entry.ptr[i], mem, endianSwap);
        }
    }

    return true;
}

inline bool Data::LoadFromFile(const char* fileName)
{
    FILE* file = nullptr;
    fopen_s(&file, fileName, "rb");
    if (!file)
        return false;

    fseek(file, 0, SEEK_END);
    uint32_t fileSize = (uint32_t)ftell(file);

    m_ownedMemory = new uint8_t[fileSize];
    fseek(file, 0, SEEK_SET);

    if (fread(m_ownedMemory, fileSize, 1, file) != 1)
        return false;

    fclose(file);

    bool ret = LoadFromMemory(m_ownedMemory, fileSize);

    return ret;
}

// ================================= Pointer Fixup =================================

inline void Data::DoEndianSwapAndPointerFixup(Pos& v, void* base, bool endianSwap)
{
    DoEndianSwapAndPointerFixup(v.x, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.y, base, endianSwap);
}

inline void Data::DoEndianSwapAndPointerFixup(EntryAll& v, void* base, bool endianSwap)
{
    DoEndianSwapAndPointerFixup(v._bool, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint8, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._int8, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint16, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._int16, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint32, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._int32, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint64, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._int64, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._float, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._double, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._color, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._pos, base, endianSwap);
}

inline void Data::DoEndianSwapAndPointerFixup(EntryDefault& v, void* base, bool endianSwap)
{
    DoEndianSwapAndPointerFixup(v._bool, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint8, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._int8, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint16, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._int16, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint32, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._int32, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint64, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._int64, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._float, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._double, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._color, base, endianSwap);
}

inline void Data::DoEndianSwapAndPointerFixup(EntryArrayDynamic& v, void* base, bool endianSwap)
{
    DoEndianSwapAndPointerFixup(v._bool_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._bool, base, endianSwap);
    for (uint32_t i = 0; i < v._bool_count; ++i)
        DoEndianSwapAndPointerFixup(v._bool.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint8_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint8, base, endianSwap);
    for (uint32_t i = 0; i < v._uint8_count; ++i)
        DoEndianSwapAndPointerFixup(v._uint8.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._int8_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._int8, base, endianSwap);
    for (uint32_t i = 0; i < v._int8_count; ++i)
        DoEndianSwapAndPointerFixup(v._int8.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint16_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint16, base, endianSwap);
    for (uint32_t i = 0; i < v._uint16_count; ++i)
        DoEndianSwapAndPointerFixup(v._uint16.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._int16_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._int16, base, endianSwap);
    for (uint32_t i = 0; i < v._int16_count; ++i)
        DoEndianSwapAndPointerFixup(v._int16.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint32_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint32, base, endianSwap);
    for (uint32_t i = 0; i < v._uint32_count; ++i)
        DoEndianSwapAndPointerFixup(v._uint32.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._int32_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._int32, base, endianSwap);
    for (uint32_t i = 0; i < v._int32_count; ++i)
        DoEndianSwapAndPointerFixup(v._int32.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint64_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._uint64, base, endianSwap);
    for (uint32_t i = 0; i < v._uint64_count; ++i)
        DoEndianSwapAndPointerFixup(v._uint64.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._int64_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._int64, base, endianSwap);
    for (uint32_t i = 0; i < v._int64_count; ++i)
        DoEndianSwapAndPointerFixup(v._int64.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._float_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._float, base, endianSwap);
    for (uint32_t i = 0; i < v._float_count; ++i)
        DoEndianSwapAndPointerFixup(v._float.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._double_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._double, base, endianSwap);
    for (uint32_t i = 0; i < v._double_count; ++i)
        DoEndianSwapAndPointerFixup(v._double.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._color_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._color, base, endianSwap);
    for (uint32_t i = 0; i < v._color_count; ++i)
        DoEndianSwapAndPointerFixup(v._color.ptr[i], base, endianSwap);
    DoEndianSwapAndPointerFixup(v._pos_count, base, endianSwap);
    DoEndianSwapAndPointerFixup(v._pos, base, endianSwap);
    for (uint32_t i = 0; i < v._pos_count; ++i)
        DoEndianSwapAndPointerFixup(v._pos.ptr[i], base, endianSwap);
}

inline void Data::DoEndianSwapAndPointerFixup(EntryArray4& v, void* base, bool endianSwap)
{
    for (uint32_t i = 0; i < v._bool_count; ++i)
        DoEndianSwapAndPointerFixup(v._bool[i], base, endianSwap);
    for (uint32_t i = 0; i < v._uint8_count; ++i)
        DoEndianSwapAndPointerFixup(v._uint8[i], base, endianSwap);
    for (uint32_t i = 0; i < v._int8_count; ++i)
        DoEndianSwapAndPointerFixup(v._int8[i], base, endianSwap);
    for (uint32_t i = 0; i < v._uint16_count; ++i)
        DoEndianSwapAndPointerFixup(v._uint16[i], base, endianSwap);
    for (uint32_t i = 0; i < v._int16_count; ++i)
        DoEndianSwapAndPointerFixup(v._int16[i], base, endianSwap);
    for (uint32_t i = 0; i < v._uint32_count; ++i)
        DoEndianSwapAndPointerFixup(v._uint32[i], base, endianSwap);
    for (uint32_t i = 0; i < v._int32_count; ++i)
        DoEndianSwapAndPointerFixup(v._int32[i], base, endianSwap);
    for (uint32_t i = 0; i < v._uint64_count; ++i)
        DoEndianSwapAndPointerFixup(v._uint64[i], base, endianSwap);
    for (uint32_t i = 0; i < v._int64_count; ++i)
        DoEndianSwapAndPointerFixup(v._int64[i], base, endianSwap);
    for (uint32_t i = 0; i < v._float_count; ++i)
        DoEndianSwapAndPointerFixup(v._float[i], base, endianSwap);
    for (uint32_t i = 0; i < v._double_count; ++i)
        DoEndianSwapAndPointerFixup(v._double[i], base, endianSwap);
    for (uint32_t i = 0; i < v._color_count; ++i)
        DoEndianSwapAndPointerFixup(v._color[i], base, endianSwap);
    for (uint32_t i = 0; i < v._pos_count; ++i)
        DoEndianSwapAndPointerFixup(v._pos[i], base, endianSwap);
}

inline void Data::DoEndianSwapAndPointerFixup(Entry& v, void* base, bool endianSwap)
{
    DoEndianSwapAndPointerFixup(v.entries, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.entries_defaults, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.entries_dynamic_arrays, base, endianSwap);
    DoEndianSwapAndPointerFixup(v.entries_static_arrays, base, endianSwap);
}

// ================================= Public Interface =================================
template <>
inline uint32_t Data::GetCount<Data::Entry>() const
{
    return m_table_Entry_count;
}

template <>
inline Data::EntryRecord Data::Get<Data::Entry>(uint32_t index) const
{
    EntryRecord ret;
    if (index < m_table_Entry_count)
    {
        ret.m_record = &m_table_Entry.ptr[index];
    }
    return ret;
}

template <>
inline Data::EntryRecord Data::Get<Data::Entry>(const char* name) const
{
    EntryRecord ret;

    Ptr64<char>* array = m_table_Entry_names.ptr;
    const uint32_t count = m_table_Entry_count;

    auto it = std::lower_bound(
        array,
        array + count,
        name,
        [](const Ptr64<char>& item, const char* val)
        {
            return strcmp(item.ptr, val) < 0;
        }
    );

    uint32_t index = uint32_t(it - array);

    if (index < count && !strcmp(it->ptr, name))
    {
        ret.m_record = &m_table_Entry.ptr[index];
    }

    return ret;
}

inline uint32_t Data::GetEntryCount() const
{
    return GetCount<Entry>();
}

inline Data::EntryRecord Data::GetEntry(uint32_t index) const
{
    return Get<Entry>(index);
}

inline Data::EntryRecord Data::GetEntry(const char* name) const
{
    return Get<Entry>(name);
}
